"""
Django settings for oar project.

Generated by 'django-admin startproject' using Django 2.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import requests
import sys

from django.db.models import options
from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers

from api.constants import NON_FIELD_ERRORS_KEY

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Compatibility: allow legacy `index_together` meta option so immutable older
# migrations (e.g., Django<5 era) continue to load without edits.
if 'index_together' not in options.DEFAULT_NAMES:
    options.DEFAULT_NAMES = (*options.DEFAULT_NAMES, 'index_together')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'secret')

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "underline", "strikethrough",
            "link", "|",
            "bulletedList", "numberedList", "|",
            "removeFormat", "|",
            "undo", "redo",
        ],
        # Remove upload/media/table plugins to mirror the prior CKEditor 4 config
        # that blocked image/file uploads and kept the toolbar minimal.
        # Only supported identifiers for django-ckeditor-5 0.2.19 are listed.
        "removePlugins": [
            "CKFinderUploadAdapter", "Image", "ImageCaption", "ImageStyle",
            "ImageToolbar", "MediaEmbed", "Table", "TableToolbar",
        ],
    }
}

# Set environment
ENVIRONMENT = os.getenv('DJANGO_ENV', 'Local')

# Set environment instance source
INSTANCE_SOURCE = os.getenv('INSTANCE_SOURCE', 'os_hub')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (ENVIRONMENT == 'Local')

VALID_ENVIRONMENTS = ('Production', 'Staging', 'Development', 'Test',
                      'Preprod', 'Rba', 'Local')
if ENVIRONMENT not in VALID_ENVIRONMENTS:
    raise ImproperlyConfigured(
        'Invalid ENVIRONMENT provided, must be one of {}'
        .format(VALID_ENVIRONMENTS))

BATCH_JOB_QUEUE_NAME = os.getenv('BATCH_JOB_QUEUE_NAME')
if BATCH_JOB_QUEUE_NAME is None and not DEBUG:
    raise ImproperlyConfigured(
        'Invalid BATCH_JOB_QUEU_NAME provided, must be set')

BATCH_JOB_DEF_NAME = os.getenv('BATCH_JOB_DEF_NAME')
if BATCH_JOB_DEF_NAME is None and not DEBUG:
    raise ImproperlyConfigured(
        'Invalid BATCH_JOB_DEF_NAME provided, must be set')

EXTERNAL_DOMAIN = os.getenv('EXTERNAL_DOMAIN')
if EXTERNAL_DOMAIN is None and not DEBUG:
    raise ImproperlyConfigured(
        'Invalid EXTERNAL_DOMAIN provided, must be set')

# A non-empty value of BATCH_MODE signals that we will only be running batch
# processing management commands
BATCH_MODE = os.getenv('BATCH_MODE', '')

LOGLEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO')

GIT_COMMIT = os.getenv('GIT_COMMIT', 'UNKNOWN')

ALLOWED_HOSTS = [
    '.openapparel.org',
    '.opensupplyhub.org',
    '.os-hub.net',
    'localhost',
]

if DEBUG:
    ALLOWED_HOSTS.append('django')
    ALLOWED_HOSTS.append('app')
    ALLOWED_HOSTS.append('contricleaner')

if not DEBUG and BATCH_MODE == '':
    # Within EC2, the Elastic Load Balancer HTTP health check will use the
    # target instance's private IP address for the Host header.
    #
    # The following steps lookup the current instance's private IP address
    # (via the EC2 instance metadata URL) and add it to the Django
    # ALLOWED_HOSTS configuration so that health checks pass.
    #
    # Beginning with version 1.17.0 of the Amazon ECS container agent,
    # tasks that use the awsvpc network mode will have to use the
    # ECS Task Metadata endpoint.

    response = requests.get('http://169.254.170.2/v2/metadata')
    if response.ok:
        response = response.json()

        for container in response['Containers']:
            for network in container['Networks']:
                for addr in network['IPv4Addresses']:
                    ALLOWED_HOSTS.append(addr)
    else:
        raise ImproperlyConfigured('Unable to fetch instance metadata')

    # Ensure Django knows to determine whether an inbound request was
    # made over HTTPS by the ALBs HTTP_X_FORWARDED_PROTO header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.gis',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_gis',
    'drf_yasg',
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'watchman',
    'simple_history',
    'waffle',
    'api',
    'web',
    'ecsmanage',
    'django_bleach',
    'django_ckeditor_5',
    'jsoneditor',
    'spa',
]

# For allauth
SITE_ID = 1
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_ADAPTER = "api.adapters.OARUserAccountAdapter"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
# https://docs.djangoproject.com/en/3.2/ref/settings/#session-cookie-age
SESSION_COOKIE_AGE = 86400 # 24 hours in seconds

AUTH_USER_MODEL = 'api.User'

SESSION_COOKIE_SECURE = True

REST_AUTH = {
    'USER_DETAILS_SERIALIZER': 'api.serializers.UserSerializer',
    'PASSWORD_RESET_SERIALIZER': 'api.serializers.UserPasswordResetSerializer',
    'PASSWORD_RESET_CONFIRM_SERIALIZER': 'api.serializers.UserPasswordResetConfirmSerializer',
}

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'rollbar.contrib.django_rest_framework.post_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'api.authentication.CsrfExemptSessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'api.permissions.IsAuthenticatedOrWebClient',
    ),
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.PageAndSizePagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'api.throttles.BurstRateThrottle',
        'api.throttles.SustainedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'burst': '100/minute',
        'sustained': '10000/day',
        'data_upload': '30/minute',
        'tiles': '300/minute',
    },
    # By default, the value of NON_FIELD_ERRORS_KEY is 'non_field_errors'.
    # It is being redefined to ensure 100% consistency between custom error
    # messages and Django's built-in ones.
    'NON_FIELD_ERRORS_KEY': NON_FIELD_ERRORS_KEY
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization',
        },
    },
    'DOC_EXPANSION': 'none',
    'USE_SESSION_AUTH': False,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Clickjacking protection is turned off to allow iframes:
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'spa.middleware.SPAMiddleware',
    'rollbar.contrib.django.middleware.RollbarNotifierMiddlewareExcluding404',
    'simple_history.middleware.HistoryRequestMiddleware',
    'waffle.middleware.WaffleMiddleware',
    'api.middleware.RequestLogMiddleware',
    'api.middleware.RequestMeterMiddleware',
    'api.middleware.OriginSourceMiddleware',
    'api.middleware.DarkVisitorsMiddleware',
]

ROOT_URLCONF = 'oar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT')
    }
}

# Use < 3+ default for ID fields
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# User model
# https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = 'api.User'

# Caching
# https://docs.djangoproject.com/en/3.2/topics/cache/

MEMCACHED_LOCATION = f"{os.getenv('CACHE_HOST')}:{os.getenv('CACHE_PORT')}"
# Use PyLibMCCache everywhere; django_elasticache is incompatible with Django 5
# because it still imports smart_text. This keeps throttling cache working in
# jobs/containers that upgrade Django.
CACHE_BACKEND = 'django.core.cache.backends.memcached.PyLibMCCache'

CACHES = {
    'default': {
        # Use the default in-memory cache when not specifying cache
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'api_throttling': {
        # Use memcached for API throttling
        'BACKEND': CACHE_BACKEND,
        'LOCATION': MEMCACHED_LOCATION
    }
}

# Logging
# https://docs.djangoproject.com/en/2.1/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] [{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Email
# https://docs.djangoproject.com/en/2.0/topics/email

AWS_DEFAULT_REGION = os.getenv('AWS_DEFAULT_REGION', 'eu-west-1')

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django_amazon_ses.EmailBackend'

DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL', 'noreply@staging.opensupplyhub.org')

DATA_FROM_EMAIL = os.getenv(
    'DATA_FROM_EMAIL', 'data@staging.opensupplyhub.org')

CLAIM_FROM_EMAIL = os.getenv(
    'CLAIM_FROM_EMAIL', 'claims@opensupplyhub.org')

NOTIFICATION_EMAIL_TO = os.getenv(
    'NOTIFICATION_EMAIL_TO', 'notification@example.com')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = ((os.path.join(STATIC_ROOT, "static")),)
STATICFILES_STORAGE = "spa.storage.SPAStaticFilesStorage"

# Watchman
# https://github.com/mwarkentin/django-watchman

WATCHMAN_ERROR_CODE = 503
WATCHMAN_CHECKS = (
    'watchman.checks.databases',
    'watchman.checks.caches',
)

# django-ecsmanage
# https://github.com/azavea/django-ecsmanage

ECSMANAGE_ENVIRONMENTS = {
    'staging': {
        'TASK_DEFINITION_NAME': 'OpenSupplyHubStagingAppCLI',
        'CONTAINER_NAME': 'django',
        'CLUSTER_NAME': 'ecsOpenSupplyHubStagingCluster',
        'LAUNCH_TYPE': 'FARGATE',
        'PLATFORM_VERSION': '1.4.0',
        'SECURITY_GROUP_TAGS': {
            'Name': 'sgAppEcsService',
            'Environment': 'Staging',
            'Project': 'OpenSupplyHub'
        },
        'SUBNET_TAGS': {
            'Name': 'PrivateSubnet',
            'Environment': 'Staging',
            'Project': 'OpenSupplyHub'
        },
        'AWS_REGION': 'eu-west-1',
    },
    'production': {
        'TASK_DEFINITION_NAME': 'OpenSupplyHubProductionAppCLI',
        'CONTAINER_NAME': 'django',
        'CLUSTER_NAME': 'ecsOpenSupplyHubProductionCluster',
        'LAUNCH_TYPE': 'FARGATE',
        'PLATFORM_VERSION': '1.4.0',
        'SECURITY_GROUP_TAGS': {
            'Name': 'sgAppEcsService',
            'Environment': 'Production',
            'Project': 'OpenSupplyHub'
        },
        'SUBNET_TAGS': {
            'Name': 'PrivateSubnet',
            'Environment': 'Production',
            'Project': 'OpenSupplyHub'
        },
        'AWS_REGION': 'eu-west-1',
    },
    'rba': {
        'TASK_DEFINITION_NAME': 'OpenSupplyHubRbaAppCLI',
        'CONTAINER_NAME': 'django',
        'CLUSTER_NAME': 'ecsOpenSupplyHubRbaCluster',
        'LAUNCH_TYPE': 'FARGATE',
        'PLATFORM_VERSION': '1.4.0',
        'SECURITY_GROUP_TAGS': {
            'Name': 'sgAppEcsService',
            'Environment': 'Rba',
            'Project': 'OpenSupplyHub'
        },
        'SUBNET_TAGS': {
            'Name': 'PrivateSubnet',
            'Environment': 'Rba',
            'Project': 'OpenSupplyHub'
        },
        'AWS_REGION': 'eu-west-1',
    },
    'test': {
        'TASK_DEFINITION_NAME': 'OpenSupplyHubTestAppCLI',
        'CONTAINER_NAME': 'django',
        'CLUSTER_NAME': 'ecsOpenSupplyHubTestCluster',
        'LAUNCH_TYPE': 'FARGATE',
        'PLATFORM_VERSION': '1.4.0',
        'SECURITY_GROUP_TAGS': {
            'Name': 'sgAppEcsService',
            'Environment': 'Test',
            'Project': 'OpenSupplyHub',
        },
        'SUBNET_TAGS': {
            'Name': 'PrivateSubnet',
            'Environment': 'Test',
            'Project': 'OpenSupplyHub',
        },
        'AWS_REGION': 'eu-west-1',
    },
    'development': {
        'TASK_DEFINITION_NAME': 'OpenSupplyHubDevelopmentAppCLI',
        'CONTAINER_NAME': 'django',
        'CLUSTER_NAME': 'ecsOpenSupplyHubDevelopmentCluster',
        'LAUNCH_TYPE': 'FARGATE',
        'PLATFORM_VERSION': '1.4.0',
        'SECURITY_GROUP_TAGS': {
            'Name': 'sgAppEcsService',
            'Environment': 'Development',
            'Project': 'OpenSupplyHub',
        },
        'SUBNET_TAGS': {
            'Name': 'PrivateSubnet',
            'Environment': 'Development',
            'Project': 'OpenSupplyHub',
        },
        'AWS_REGION': 'eu-west-1',
    },
    'preprod': {
        'TASK_DEFINITION_NAME': 'OpenSupplyHubPreprodAppCLI',
        'CONTAINER_NAME': 'django',
        'CLUSTER_NAME': 'ecsOpenSupplyHubPreprodCluster',
        'LAUNCH_TYPE': 'FARGATE',
        'PLATFORM_VERSION': '1.4.0',
        'SECURITY_GROUP_TAGS': {
            'Name': 'sgAppEcsService',
            'Environment': 'Preprod',
            'Project': 'OpenSupplyHub',
        },
        'SUBNET_TAGS': {
            'Name': 'PrivateSubnet',
            'Environment': 'Preprod',
            'Project': 'OpenSupplyHub',
        },
        'AWS_REGION': 'eu-west-1',
    },
}

# Application settings
MAX_UPLOADED_FILE_SIZE_IN_BYTES = 5242880
MAX_ATTACHMENT_SIZE_IN_BYTES = 5 * 1024 * 1024 # 5 MB
MAX_ATTACHMENT_AMOUNT = 20
ALLOWED_ATTACHMENT_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.pdf']
TILE_CACHE_MAX_AGE_IN_SECONDS = 60 * 60 * 24 * 365 # 1 year. Also in deployment/terraform/cdn.tf  # NOQA
DUPLICATE_THROTTLE_TIMEOUT = 900 # 15 minutes

GOOGLE_SERVER_SIDE_API_KEY = os.getenv('GOOGLE_SERVER_SIDE_API_KEY')
if GOOGLE_SERVER_SIDE_API_KEY is None:
    raise ImproperlyConfigured(
        'Invalid GOOGLE_SERVER_SIDE_API_KEY provided, must be set')

if not DEBUG:
    ROLLBAR = {
        'access_token': os.getenv('ROLLBAR_SERVER_SIDE_ACCESS_TOKEN'),
        'environment': ENVIRONMENT.lower(),
        'root': BASE_DIR,
        'suppress_reinit_warning': True,
        'capture_ip': False
    }
    import rollbar
    rollbar.init(**ROLLBAR)

OAR_CLIENT_KEY = os.getenv('OAR_CLIENT_KEY')

if OAR_CLIENT_KEY is None:
    raise ImproperlyConfigured(
        'Invalid OAR_CLIENT_KEY provided, must be set')

# Hubspot settings
raw_hubspot_key = os.getenv('HUBSPOT_API_KEY')
HUBSPOT_API_KEY = raw_hubspot_key if raw_hubspot_key else None

raw_hubspot_id = os.getenv('HUBSPOT_SUBSCRIPTION_ID')
HUBSPOT_SUBSCRIPTION_ID = raw_hubspot_id if raw_hubspot_id else None

# CORS
# Regex defining which endpoints enable CORS
CORS_URLS_REGEX = r"^/api/info/.*$"
# allows X-OAR-Client-Key to be sent as a header on CORS requests
CORS_ALLOW_HEADERS = list(default_headers) + [
    'X-OAR-Client-Key',
]
# methods that can be used at CORS-enabled endpoints
CORS_ALLOW_METHODS = [
    "GET",
    "OPTIONS",
]
# origins that are authorized to make cross-site HTTP
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://\w+\.openapparel\.org$",
    r"^https://\w+\.opensupplyhub\.org$",
    r"^https://oar\.niceandserious\.com$",
    r"^https://dev\.os-hub\.net$",
    r"^http://localhost",
    r"http://127.0.0.1",
]
# CORS_ALLOWED_ORIGIN_REGEXES = json.loads(os.getenv('CORS_ALLOWED_ORIGIN_REGEXES'))


# django-storages
# Reference # https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html

AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')

if DEBUG and AWS_S3_ENDPOINT_URL:
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_S3_USE_SSL = False

AWS_S3_FILE_OVERWRITE = False

TESTING = 'test' in sys.argv

# Use filesystem for "default" when running tests (so tests never use S3/MinIO) or
# when DEBUG and no S3 endpoint (local without MinIO). Use S3 when not DEBUG or
# when DEBUG but AWS_S3_ENDPOINT_URL is set (e.g. reset_database with MinIO).
if (DEBUG and not AWS_S3_ENDPOINT_URL) or TESTING:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": os.path.join(BASE_DIR, "media"),
            },
        },
        "staticfiles": {
            "BACKEND": "spa.storage.SPAStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "spa.storage.SPAStaticFilesStorage",
        },
    }

AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')

if AWS_STORAGE_BUCKET_NAME is None and not DEBUG:
    raise ImproperlyConfigured(
        'Invalid AWS_STORAGE_BUCKET_NAME provided, must be set in the environment'
    )

TEST_RUNNER = 'django_slowtests.testrunner.DiscoverSlowestTestsRunner'
NUM_SLOW_TESTS = 10

# (Optional)
SLOW_TEST_THRESHOLD_MS = 200  # Only show tests slower than 200ms

# (Optional)
ALWAYS_GENERATE_SLOW_REPORT = True  # Generate report only when requested using --slowreport flag

KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS', '') # Kafka servers to connect
KAFKA_TOPIC_DEDUPE_BASIC_NAME = os.getenv('KAFKA_TOPIC_DEDUPE_BASIC_NAME', '') # Kafka Dedupe Hub Topic

# Django Bleach settings
# https://django-bleach.readthedocs.io/en/latest/
BLEACH_ALLOWED_TAGS = [
    'p', 'br', 'em', 'strong', 'ins', 'del', 'code', 'sup', 'sub',
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'pre',
    'ul', 'ol', 'li', 'a',
]

BLEACH_ALLOWED_ATTRIBUTES = {
    'a': ['href', 'target', 'title'],
}

BLEACH_STRIP_TAGS = True

BLEACH_STRIP_COMMENTS = True

# Stripe settings
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
STRIPE_PRICE_ID = os.getenv('STRIPE_PRICE_ID')

# Dark Visitors settings
DARK_VISITORS_PROJECT_KEY = os.getenv('DARK_VISITORS_PROJECT_KEY', '')
DARK_VISITORS_TOKEN = os.getenv('DARK_VISITORS_TOKEN', '')

# Email anonymization secret for the sync_databases management command.
EMAIL_ANONYMIZATION_SECRET = os.getenv('EMAIL_ANONYMIZATION_SECRET', '')
