version: '3.8'

networks:
  proxynet:
    name: os-hub-development
    external: true  # Important to reuse the existing network

services:
  rba_db:
    build:
      context: ./src/database
      dockerfile: Dockerfile.local
    container_name: rba_db
    environment:
      POSTGRES_DB: rba
      POSTGRES_USER: opensupplyhub
      POSTGRES_PASSWORD: opensupplyhub
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "opensupplyhub"]
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - rba_data:/var/lib/postgresql/data
      - ./dumps:/dumps
    ports:
      - "5434:5432"
    networks:
      - proxynet

volumes:
  rba_data:
