networks:
  my-proxy-net:
    external:
      name: os-hub-development

services:
  integration-test:
    build:
      context: ./src/tests
      dockerfile: Dockerfile
    environment:
      - OPENSEARCH_HOST=opensearch-single-node
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_MODERATION_EVENTS_INDEX=moderation-events
      - OPENSEARCH_PRODUCTION_LOCATIONS_INDEX=production-locations
      - REACT_HOST=react
      - REACT_PORT=6543
      - ADMIN_API_TOKEN=4687eec6fc6389a769a71ca415cdfb026ccd0bec
      - USER_API_TOKEN=4687eec6fc6389a769a71ca415cdfb026ccd0bec
    command: uvicorn main:app --host 0.0.0.0 --port 84
    networks:
      - my-proxy-net

  playwright-test:
    build:
      context: ./src/e2e
      dockerfile: Dockerfile
    environment:
      - CI=$CI
    networks:
      - my-proxy-net
