#!/bin/bash

sudo yum update -y
sudo yum install -y docker
sudo systemctl enable docker
sudo systemctl start docker
sudo usermod -aG docker ec2-user
sudo mkdir -p /usr/libexec/docker/cli-plugins
sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-aarch64 \
  -o /usr/libexec/docker/cli-plugins/docker-compose
sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose


# Check docker compose
docker compose version

# 4. TODOGrab the official docker compose file

# 5. (IMPORTANT) Set your public IP or domain in the WG_HOST env var
# Either edit the docker-compose.yml file:
nano docker-compose.yml
# Replace:
#   - WG_HOST=raspberrypi.local
# With:
#   - WG_HOST=<your-EC2-public-IP-or-domain>

# 6. Run the container
sudo docker compose up -d