#!/bin/bash

# -- Check if the dump file path and first path are provided as arguments
# -- if [ "$#" -ne 2 ]; then
# --    echo "Usage: $0 <first_path> <dump_file_path>"
# --    exit 1
# -- fi

# -- Assign the provided paths to variables
# -- RESET_FILE_PATH="$1"
# -- DUMP_FILE_PATH="$2"

echo "Running anonymize script"
# Drop anondb database
docker exec -i anonymizer-database-1 dropdb -U anondb anondb

# Drop anondb database
docker exec -i anonymizer-database-1 createdb -U anondb anondb

# Restore anondb database from the restore file
# -- docker exec -i anonymize_database-1 pg_restore -U anondb -d anondb < "$RESET_FILE_PATH"
docker exec -i anonymizer-database-1 pg_restore -U anondb -d anondb < ../db_before/dump.dump

# SQL script for updating email fields
SQL_SCRIPT="DO \$\$
DECLARE
    current_table text;
    column_exists_email boolean;
    column_exists_username boolean;
    column_exists_password boolean;
    column_exists_phone_number boolean;
BEGIN
    FOR current_table IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public')
    LOOP
        EXECUTE 'SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = ''' || current_table || ''' AND column_name = ''email'')' INTO column_exists_email;
        EXECUTE 'SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = ''' || current_table || ''' AND column_name = ''username'')' INTO column_exists_username;
        EXECUTE 'SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = ''' || current_table || ''' AND column_name = ''password'')' INTO column_exists_password;
        EXECUTE 'SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = ''' || current_table || ''' AND column_name = ''phone_number'')' INTO column_exists_phone_number;

        IF column_exists_email THEN
            EXECUTE 'UPDATE ' || current_table || ' SET 
                email = CASE WHEN email NOT LIKE ''%@speedandfuncion.com'' AND email NOT LIKE ''%@opensupplyhub.com'' THEN md5(random()::text) || ''@'' || substring(email from position(''@'' in email) + 1) ELSE email END';

            IF column_exists_username THEN
                EXECUTE 'UPDATE ' || current_table || ' SET 
                    username = CASE WHEN email NOT LIKE ''%@speedandfuncion.com'' AND email NOT LIKE ''%@opensupplyhub.com'' THEN substr(md5(random()::text), 1, 20) ELSE username END';
            END IF;

            IF column_exists_password THEN
                EXECUTE 'UPDATE ' || current_table || ' SET 
                    password = CASE WHEN email NOT LIKE ''%@speedandfuncion.com'' AND email NOT LIKE ''%@opensupplyhub.com'' THEN md5(random()::text) ELSE password END';
            END IF;

            IF column_exists_phone_number THEN
                EXECUTE 'UPDATE ' || current_table || ' SET 
                    phone_number = CASE WHEN email NOT LIKE ''%@speedandfuncion.com'' AND email NOT LIKE ''%@opensupplyhub.com'' THEN md5(random()::text) ELSE phone_number END';
            END IF;
        END IF;
    END LOOP;
END \$\$;"


# Execute SQL script and create a dump file
# -- docker exec -it anonymize_database-1 psql -U anondb -d anondb -c "$SQL_SCRIPT" && sudo docker exec -it anonymize_database-1 pg_dump -U anondb -d anondb -f "$DUMP_FILE_PATH"
docker exec -it anonymize_database-1 psql -U anondb -d anondb -c "$SQL_SCRIPT" && sudo docker exec -it anonymize_database-1 pg_dump -U anondb -d anondb -f ../db_after/anonymized_dump.dump
