import COLOURS from '../../util/COLOURS';

/*
 * Styles for the claims dashboard v2 (OSDEV-3355/3356). Plain frozen
 * style objects, matching Dashboard.jsx's approach; visual spec:
 * https://claims-moderation-prototype.vercel.app
 *
 * Type scale: 16px base / 13.5px secondary / 13px hints — the
 * prototype's hierarchy (uppercase letterspaced section labels,
 * 600-weight card titles, muted metas) at a substantially larger size
 * for readability at moderation-session lengths.
 */

export default Object.freeze({
    shell: Object.freeze({
        display: 'flex',
        alignItems: 'flex-start',
        gap: '16px',
        padding: '8px 0 16px',
    }),
    sectionLabel: Object.freeze({
        textTransform: 'uppercase',
        letterSpacing: '.07em',
        fontWeight: 700,
        fontSize: '13px',
        color: COLOURS.DARK_GREY,
        margin: '4px 0 8px',
    }),
    rail: Object.freeze({
        width: '320px',
        flex: 'none',
    }),
    railCollapsed: Object.freeze({
        width: '44px',
        flex: 'none',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '8px',
    }),
    railToggle: Object.freeze({
        padding: '4px 9px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '14px',
    }),
    railCollapsedCount: Object.freeze({
        writingMode: 'vertical-rl',
        color: COLOURS.DARK_GREY,
        fontSize: '13px',
    }),
    railCard: Object.freeze({
        display: 'block',
        width: '100%',
        textAlign: 'left',
        padding: '10px 12px',
        marginBottom: '6px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '16px',
        fontWeight: 600,
    }),
    railCardSelected: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
    }),
    railCardMeta: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontSize: '13.5px',
        fontWeight: 400,
        marginTop: '2px',
    }),
    workspace: Object.freeze({
        flex: 1,
        minWidth: 0,
    }),
    topGrid: Object.freeze({
        display: 'flex',
        alignItems: 'flex-start',
        gap: '16px',
        margin: '12px 0',
    }),
    topGridMain: Object.freeze({
        flex: 1,
        minWidth: 0,
    }),
    decisionRail: Object.freeze({
        // Spec §5b: the Decision rail is ~38% of the top grid.
        flex: 'none',
        width: '38%',
        padding: '12px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
    }),
    decisionButtons: Object.freeze({
        display: 'flex',
        gap: '8px',
        margin: '10px 0',
    }),
    approveButton: Object.freeze({
        flex: 1,
        padding: '10px 12px',
        border: 'none',
        borderRadius: '6px',
        background: COLOURS.NAVY_BLUE,
        color: COLOURS.WHITE,
        cursor: 'pointer',
        fontWeight: 700,
        fontSize: '15px',
    }),
    denyButton: Object.freeze({
        flex: 1,
        padding: '10px 12px',
        border: `1px solid ${COLOURS.RED}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        color: COLOURS.RED,
        cursor: 'pointer',
        fontWeight: 700,
        fontSize: '15px',
    }),
    jiraBox: Object.freeze({
        padding: '10px 12px',
        margin: '8px 0',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '15px',
    }),
    claimantFacingWarning: Object.freeze({
        padding: '10px 12px',
        margin: '4px 0 10px',
        border: `1px solid ${COLOURS.RED}`,
        borderRadius: '6px',
        background: COLOURS.LIGHT_RED,
    }),
    dialogTextarea: Object.freeze({
        width: '100%',
        minHeight: '140px',
        resize: 'vertical',
        padding: '10px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '16px',
        fontFamily: 'inherit',
        boxSizing: 'border-box',
        marginTop: '10px',
    }),
    dialogTextareaSmall: Object.freeze({
        width: '100%',
        minHeight: '80px',
        resize: 'vertical',
        padding: '10px',
        border: `1px dashed ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '15px',
        fontFamily: 'inherit',
        boxSizing: 'border-box',
        marginTop: '10px',
    }),
    stageBox: Object.freeze({
        padding: '10px 12px',
        margin: '8px 0',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.LIGHT_GREY,
        fontSize: '15px',
    }),
    noteItem: Object.freeze({
        padding: '10px 0',
        borderTop: `1px solid ${COLOURS.GREY}`,
        fontSize: '16px',
    }),
    noteTag: Object.freeze({
        display: 'inline-block',
        marginLeft: '6px',
        padding: '2px 8px',
        borderRadius: '4px',
        fontSize: '12.5px',
        fontWeight: 700,
        background: COLOURS.LIGHT_GREY,
    }),
    noteMeta: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontSize: '13.5px',
    }),
    railSearch: Object.freeze({
        width: '100%',
        padding: '8px 10px',
        marginBottom: '6px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '15px',
        boxSizing: 'border-box',
    }),
    railControls: Object.freeze({
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        marginBottom: '8px',
    }),
    railCountLine: Object.freeze({
        minWidth: 0,
    }),
    railSelect: Object.freeze({
        flex: 1,
        minWidth: 0,
        padding: '6px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        fontSize: '14px',
    }),
    railSortButton: Object.freeze({
        flex: 'none',
        padding: '6px 10px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '14px',
    }),
    stageHead: Object.freeze({
        display: 'flex',
        justifyContent: 'space-between',
        width: '100%',
        padding: '8px 10px',
        margin: '10px 0 6px',
        border: 'none',
        borderRadius: '4px',
        background: COLOURS.LIGHT_GREY,
        cursor: 'pointer',
        fontWeight: 700,
        fontSize: '13.5px',
        textTransform: 'uppercase',
        letterSpacing: '.06em',
        textAlign: 'left',
    }),
    stageAccentNew: Object.freeze({
        borderLeft: `4px solid ${COLOURS.NAVY_BLUE}`,
    }),
    stageAccentAwaiting: Object.freeze({
        borderLeft: `4px solid ${COLOURS.DARK_GREY}`,
    }),
    stageAccentOverdue: Object.freeze({
        borderLeft: `4px solid ${COLOURS.RED}`,
    }),
    stageCount: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontWeight: 400,
    }),
    stageEmpty: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontSize: '13.5px',
        padding: '2px 10px 6px',
    }),
    waitingBadge: Object.freeze({
        display: 'inline-block',
        marginLeft: '6px',
        padding: '2px 7px',
        borderRadius: '4px',
        fontSize: '12.5px',
        fontWeight: 700,
        background: COLOURS.LIGHT_GREY,
    }),
    kbdHint: Object.freeze({
        marginTop: '10px',
        color: COLOURS.DARK_GREY,
        fontSize: '13px',
    }),
    workbench: Object.freeze({
        display: 'flex',
        alignItems: 'flex-start',
        gap: '16px',
        margin: '16px 0',
        padding: '12px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
    }),
    evidenceHalf: Object.freeze({
        flex: 1,
        minWidth: 0,
    }),
    composerHalf: Object.freeze({
        flex: 1,
        minWidth: 0,
    }),
    evidenceStrip: Object.freeze({
        display: 'flex',
        flexWrap: 'wrap',
        gap: '6px',
        margin: '8px 0',
    }),
    evidenceChip: Object.freeze({
        padding: '6px 12px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '14px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '14px',
    }),
    evidenceChipOpen: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
        fontWeight: 700,
    }),
    evidenceViewer: Object.freeze({
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.LIGHT_GREY,
        padding: '10px',
    }),
    evidenceViewerBar: Object.freeze({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '8px',
        marginBottom: '6px',
    }),
    evidenceViewerName: Object.freeze({
        fontSize: '14px',
        fontWeight: 700,
        overflowWrap: 'anywhere',
    }),
    evidenceTab: Object.freeze({
        padding: '4px 10px',
        marginLeft: '4px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '4px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '14px',
    }),
    evidenceTabActive: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
        fontWeight: 700,
    }),
    evidenceClose: Object.freeze({
        marginLeft: '8px',
        border: 'none',
        background: 'none',
        cursor: 'pointer',
        fontSize: '15px',
    }),
    evidenceText: Object.freeze({
        margin: 0,
        maxHeight: '560px',
        overflow: 'auto',
        whiteSpace: 'pre-wrap',
        overflowWrap: 'anywhere',
        fontSize: '15px',
        lineHeight: 1.5,
        fontFamily: 'inherit',
        background: COLOURS.WHITE,
        padding: '10px',
        borderRadius: '4px',
    }),
    evidenceImage: Object.freeze({
        maxWidth: '100%',
        maxHeight: '560px',
        display: 'block',
        borderRadius: '4px',
    }),
    evidenceHint: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontSize: '13.5px',
    }),
    templateChips: Object.freeze({
        display: 'flex',
        flexWrap: 'wrap',
        gap: '6px',
        margin: '8px 0',
    }),
    templateChip: Object.freeze({
        padding: '6px 12px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '14px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '15px',
    }),
    templateChipSelected: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
        fontWeight: 700,
    }),
    templateChipLocked: Object.freeze({
        opacity: 0.5,
        cursor: 'not-allowed',
    }),
    suggestedDraftChip: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
    }),
    composerTextarea: Object.freeze({
        width: '100%',
        minHeight: '240px',
        resize: 'vertical',
        padding: '10px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '16px',
        lineHeight: 1.5,
        fontFamily: 'inherit',
        boxSizing: 'border-box',
    }),
    composerActions: Object.freeze({
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '8px',
        marginTop: '6px',
    }),
    composerClear: Object.freeze({
        padding: '8px 14px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '15px',
    }),
    composerSend: Object.freeze({
        padding: '8px 16px',
        border: 'none',
        borderRadius: '6px',
        background: COLOURS.NAVY_BLUE,
        color: COLOURS.WHITE,
        cursor: 'pointer',
        fontWeight: 700,
        fontSize: '15px',
    }),
    verificationTable: Object.freeze({
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        overflow: 'hidden',
    }),
    verificationRow: Object.freeze({
        display: 'flex',
        alignItems: 'flex-start',
        gap: '12px',
        padding: '10px 12px',
        borderBottom: `1px solid ${COLOURS.GREY}`,
        fontSize: '15px',
    }),
    verificationLabel: Object.freeze({
        flex: 'none',
        width: '105px',
        fontWeight: 700,
        fontSize: '13.5px',
        color: COLOURS.DARK_GREY,
        paddingTop: '2px',
    }),
    verificationValue: Object.freeze({
        flex: 1,
        minWidth: 0,
        overflowWrap: 'anywhere',
    }),
    verificationStatus: Object.freeze({
        flex: 1.4,
        minWidth: 0,
    }),
    verificationChip: Object.freeze({
        display: 'inline-block',
        padding: '3px 10px',
        borderRadius: '8px',
        fontSize: '13.5px',
        fontWeight: 700,
        lineHeight: 1.45,
    }),
    verificationChipPass: Object.freeze({
        background: COLOURS.GREEN,
        color: COLOURS.MATERIAL_GREEN,
    }),
    verificationChipCheck: Object.freeze({
        // Advisory amber, never red (SPEC.md §5a).
        background: COLOURS.PALE_LIGHT_YELLOW,
        color: '#8a6d1a',
    }),
    verificationChipNone: Object.freeze({
        background: COLOURS.LIGHT_GREY,
        color: COLOURS.DARK_GREY,
    }),
    verificationReasoning: Object.freeze({
        marginTop: '4px',
        color: COLOURS.DARK_GREY,
        fontSize: '13.5px',
    }),
    verificationFootnote: Object.freeze({
        marginTop: '4px',
        color: COLOURS.DARK_GREY,
        fontSize: '13px',
        fontStyle: 'italic',
    }),
    internalNoteBox: Object.freeze({
        margin: '10px 0',
        padding: '10px 12px',
        border: `1px dashed ${COLOURS.GREY}`,
        borderRadius: '6px',
    }),
    internalNoteTextarea: Object.freeze({
        width: '100%',
        minHeight: '70px',
        resize: 'vertical',
        padding: '10px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '15px',
        fontFamily: 'inherit',
        boxSizing: 'border-box',
    }),
    profileAnchor: Object.freeze({
        padding: '12px 14px',
        margin: '8px 0',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
    }),
    profileName: Object.freeze({
        fontWeight: 700,
        fontSize: '17px',
    }),
    profileAddress: Object.freeze({
        margin: '2px 0 6px',
    }),
    profileOsId: Object.freeze({
        fontSize: '14px',
    }),
    workspaceSub: Object.freeze({
        margin: '2px 0',
        color: COLOURS.DARK_GREY,
        fontSize: '14.5px',
    }),
    viewerBody: Object.freeze({
        display: 'flex',
        alignItems: 'flex-start',
        gap: '12px',
    }),
    viewerContent: Object.freeze({
        flex: 1.6,
        minWidth: 0,
    }),
    viewerCaption: Object.freeze({
        marginTop: '4px',
        color: COLOURS.DARK_GREY,
        fontSize: '12.5px',
    }),
    matchBox: Object.freeze({
        flex: 1,
        minWidth: '220px',
        padding: '10px 12px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        fontSize: '13.5px',
    }),
    matchTitle: Object.freeze({
        fontWeight: 700,
        marginBottom: '6px',
        fontSize: '13px',
    }),
    matchRow: Object.freeze({
        display: 'flex',
        gap: '8px',
        padding: '3px 0',
    }),
    matchKey: Object.freeze({
        flex: 'none',
        width: '96px',
        color: COLOURS.DARK_GREY,
    }),
    matchValue: Object.freeze({
        minWidth: 0,
        overflowWrap: 'anywhere',
    }),
    decisionButtonSub: Object.freeze({
        display: 'block',
        fontWeight: 400,
        fontSize: '12.5px',
        marginTop: '2px',
        opacity: 0.85,
    }),
    provenanceTag: Object.freeze({
        display: 'inline-block',
        marginBottom: '2px',
        padding: '0 6px',
        borderRadius: '4px',
        background: COLOURS.LIGHT_GREY,
        color: COLOURS.DARK_GREY,
        fontSize: '11.5px',
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: '.05em',
    }),
    counterpartLine: Object.freeze({
        marginTop: '3px',
        color: COLOURS.DARK_GREY,
        fontSize: '13px',
    }),
    detailKey: Object.freeze({
        flex: 'none',
        width: '170px',
        color: COLOURS.DARK_GREY,
    }),
    detailToggle: Object.freeze({
        display: 'block',
        width: '100%',
        textAlign: 'left',
        border: 'none',
        background: 'none',
        padding: 0,
        cursor: 'pointer',
    }),
    docSourceLink: Object.freeze({
        marginLeft: '8px',
        padding: '1px 8px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '10px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '12.5px',
    }),
});
