import COLOURS from '../../util/COLOURS';

/*
 * Styles for the claims dashboard v2 (OSDEV-3355/3356). Plain frozen
 * style objects, matching Dashboard.jsx's approach; visual spec:
 * https://claims-moderation-prototype.vercel.app
 *
 * Type scale: 15px base / 13px secondary / 12.5px hints — kept a step
 * larger than the prototype for readability at moderation-session
 * lengths.
 */

export default Object.freeze({
    shell: Object.freeze({
        display: 'flex',
        alignItems: 'flex-start',
        gap: '16px',
        padding: '16px',
        fontSize: '15px',
        lineHeight: 1.45,
    }),
    rail: Object.freeze({
        width: '320px',
        flex: 'none',
    }),
    railCollapsed: Object.freeze({
        width: '44px',
        flex: 'none',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '8px',
    }),
    railToggle: Object.freeze({
        padding: '4px 9px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '14px',
    }),
    railCollapsedCount: Object.freeze({
        writingMode: 'vertical-rl',
        color: COLOURS.DARK_GREY,
        fontSize: '13px',
    }),
    railCard: Object.freeze({
        display: 'block',
        width: '100%',
        textAlign: 'left',
        padding: '10px 12px',
        marginBottom: '6px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '15px',
    }),
    railCardSelected: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
    }),
    railCardMeta: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontSize: '13px',
        marginTop: '2px',
    }),
    workspace: Object.freeze({
        flex: 1,
        minWidth: 0,
    }),
    topGrid: Object.freeze({
        display: 'flex',
        alignItems: 'flex-start',
        gap: '16px',
        margin: '12px 0',
    }),
    topGridMain: Object.freeze({
        flex: 1,
        minWidth: 0,
    }),
    decisionRail: Object.freeze({
        // Spec §5b: the Decision rail is ~38% of the top grid.
        flex: 'none',
        width: '38%',
        padding: '12px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
    }),
    decisionButtons: Object.freeze({
        display: 'flex',
        gap: '8px',
        margin: '10px 0',
    }),
    approveButton: Object.freeze({
        flex: 1,
        padding: '10px 12px',
        border: 'none',
        borderRadius: '6px',
        background: COLOURS.NAVY_BLUE,
        color: COLOURS.WHITE,
        cursor: 'pointer',
        fontWeight: 700,
        fontSize: '14px',
    }),
    denyButton: Object.freeze({
        flex: 1,
        padding: '10px 12px',
        border: `1px solid ${COLOURS.RED}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        color: COLOURS.RED,
        cursor: 'pointer',
        fontWeight: 700,
        fontSize: '14px',
    }),
    jiraBox: Object.freeze({
        padding: '10px 12px',
        margin: '8px 0',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '14px',
    }),
    claimantFacingWarning: Object.freeze({
        padding: '10px 12px',
        margin: '4px 0 10px',
        border: `1px solid ${COLOURS.RED}`,
        borderRadius: '6px',
        background: COLOURS.LIGHT_RED,
    }),
    dialogTextarea: Object.freeze({
        width: '100%',
        minHeight: '140px',
        resize: 'vertical',
        padding: '10px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '15px',
        fontFamily: 'inherit',
        boxSizing: 'border-box',
        marginTop: '10px',
    }),
    dialogTextareaSmall: Object.freeze({
        width: '100%',
        minHeight: '80px',
        resize: 'vertical',
        padding: '10px',
        border: `1px dashed ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '14px',
        fontFamily: 'inherit',
        boxSizing: 'border-box',
        marginTop: '10px',
    }),
    stageBox: Object.freeze({
        padding: '10px 12px',
        margin: '8px 0',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.LIGHT_GREY,
        fontSize: '14px',
    }),
    noteItem: Object.freeze({
        padding: '10px 0',
        borderTop: `1px solid ${COLOURS.GREY}`,
        fontSize: '15px',
    }),
    noteTag: Object.freeze({
        display: 'inline-block',
        marginLeft: '6px',
        padding: '1px 7px',
        borderRadius: '4px',
        fontSize: '12px',
        fontWeight: 700,
        background: COLOURS.LIGHT_GREY,
    }),
    noteMeta: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontSize: '13px',
    }),
    railSearch: Object.freeze({
        width: '100%',
        padding: '8px 10px',
        marginBottom: '6px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '14px',
        boxSizing: 'border-box',
    }),
    railControls: Object.freeze({
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        marginBottom: '8px',
    }),
    railCountLine: Object.freeze({
        minWidth: 0,
    }),
    railSelect: Object.freeze({
        flex: 1,
        minWidth: 0,
        padding: '6px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        fontSize: '13px',
    }),
    railSortButton: Object.freeze({
        flex: 'none',
        padding: '6px 10px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '13px',
    }),
    stageHead: Object.freeze({
        display: 'flex',
        justifyContent: 'space-between',
        width: '100%',
        padding: '8px 10px',
        margin: '10px 0 6px',
        border: 'none',
        borderRadius: '4px',
        background: COLOURS.LIGHT_GREY,
        cursor: 'pointer',
        fontWeight: 700,
        fontSize: '13.5px',
        textAlign: 'left',
    }),
    stageAccentNew: Object.freeze({
        borderLeft: `4px solid ${COLOURS.NAVY_BLUE}`,
    }),
    stageAccentAwaiting: Object.freeze({
        borderLeft: `4px solid ${COLOURS.DARK_GREY}`,
    }),
    stageAccentOverdue: Object.freeze({
        borderLeft: `4px solid ${COLOURS.RED}`,
    }),
    stageCount: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontWeight: 400,
    }),
    stageEmpty: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontSize: '13px',
        padding: '2px 10px 6px',
    }),
    waitingBadge: Object.freeze({
        display: 'inline-block',
        marginLeft: '6px',
        padding: '1px 6px',
        borderRadius: '4px',
        fontSize: '12px',
        fontWeight: 700,
        background: COLOURS.LIGHT_GREY,
    }),
    kbdHint: Object.freeze({
        marginTop: '10px',
        color: COLOURS.DARK_GREY,
        fontSize: '12.5px',
    }),
    workbench: Object.freeze({
        display: 'flex',
        alignItems: 'flex-start',
        gap: '16px',
        margin: '16px 0',
        padding: '12px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
    }),
    evidenceHalf: Object.freeze({
        flex: 1,
        minWidth: 0,
    }),
    composerHalf: Object.freeze({
        flex: 1,
        minWidth: 0,
    }),
    evidenceStrip: Object.freeze({
        display: 'flex',
        flexWrap: 'wrap',
        gap: '6px',
        margin: '8px 0',
    }),
    evidenceChip: Object.freeze({
        padding: '6px 12px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '14px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '13px',
    }),
    evidenceChipOpen: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
        fontWeight: 700,
    }),
    evidenceViewer: Object.freeze({
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.LIGHT_GREY,
        padding: '10px',
    }),
    evidenceViewerBar: Object.freeze({
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '8px',
        marginBottom: '6px',
    }),
    evidenceViewerName: Object.freeze({
        fontSize: '13px',
        fontWeight: 700,
        overflowWrap: 'anywhere',
    }),
    evidenceTab: Object.freeze({
        padding: '4px 10px',
        marginLeft: '4px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '4px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '12.5px',
    }),
    evidenceTabActive: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
        fontWeight: 700,
    }),
    evidenceClose: Object.freeze({
        marginLeft: '8px',
        border: 'none',
        background: 'none',
        cursor: 'pointer',
        fontSize: '15px',
    }),
    evidenceText: Object.freeze({
        margin: 0,
        maxHeight: '360px',
        overflow: 'auto',
        whiteSpace: 'pre-wrap',
        overflowWrap: 'anywhere',
        fontSize: '14px',
        lineHeight: 1.5,
        fontFamily: 'inherit',
        background: COLOURS.WHITE,
        padding: '10px',
        borderRadius: '4px',
    }),
    evidenceImage: Object.freeze({
        maxWidth: '100%',
        maxHeight: '360px',
        display: 'block',
        borderRadius: '4px',
    }),
    evidenceHint: Object.freeze({
        color: COLOURS.DARK_GREY,
        fontSize: '13px',
    }),
    templateChips: Object.freeze({
        display: 'flex',
        flexWrap: 'wrap',
        gap: '6px',
        margin: '8px 0',
    }),
    templateChip: Object.freeze({
        padding: '6px 12px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '14px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '13px',
    }),
    templateChipSelected: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
        fontWeight: 700,
    }),
    templateChipLocked: Object.freeze({
        opacity: 0.5,
        cursor: 'not-allowed',
    }),
    suggestedDraftChip: Object.freeze({
        borderColor: COLOURS.NAVY_BLUE,
    }),
    composerTextarea: Object.freeze({
        width: '100%',
        minHeight: '240px',
        resize: 'vertical',
        padding: '10px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        fontSize: '15px',
        lineHeight: 1.5,
        fontFamily: 'inherit',
        boxSizing: 'border-box',
    }),
    composerActions: Object.freeze({
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '8px',
        marginTop: '6px',
    }),
    composerClear: Object.freeze({
        padding: '8px 14px',
        border: `1px solid ${COLOURS.GREY}`,
        borderRadius: '6px',
        background: COLOURS.WHITE,
        cursor: 'pointer',
        fontSize: '14px',
    }),
    composerSend: Object.freeze({
        padding: '8px 16px',
        border: 'none',
        borderRadius: '6px',
        background: COLOURS.NAVY_BLUE,
        color: COLOURS.WHITE,
        cursor: 'pointer',
        fontWeight: 700,
        fontSize: '14px',
    }),
});
