# Generated by Django 2.2.23 on 2021-08-23 14:11

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_make_period_start_date_editable'),
    ]

    operations = [
    ]
