# Generated by Django 2.2.24 on 2022-05-31 15:21

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models
from django.db.models import F, Func, OuterRef, Subquery

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_add_sector_to_facility_list_item'),
    ]

    operations = [
    ]
