# Generated by Django 3.2.4 on 2023-07-12 13:00

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import os
from django.db import connection
from django.db import transaction
from django.db import migrations, models

def create_format_numbers_of_workers_func(apps, schema_editor):
    file_path = os.path.join('./sqls/', 'format_numbers_of_workers.sql')
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
       c.execute(sql_statement)

def drop_format_numbers_of_workers_func(apps, schema_editor):
    with connection.cursor() as c:
       c.execute('drop function format_numbers_of_workers;')

def create_index_facilities_procedure(apps, schema_editor):
    file_path = os.path.join('./sqls/', 'index_facilities.sql')
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
       c.execute(sql_statement)

def drop_index_facilities_procedure(apps, schema_editor):
    with connection.cursor() as c:
       c.execute('drop procedure index_facilities;')

def create_index_facilities_by_procedure(apps, schema_editor):
    file_path = os.path.join('./sqls/', 'index_facilities_by.sql')
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
       c.execute(sql_statement)

def drop_index_facilities_by_procedure(apps, schema_editor):
    with connection.cursor() as c:
       c.execute('drop procedure index_facilities_by;')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_add_facility_index_new'),
    ]

    operations = [
        migrations.RunPython(create_format_numbers_of_workers_func, drop_format_numbers_of_workers_func),
        migrations.RunPython(create_index_facilities_procedure, drop_index_facilities_procedure),
        migrations.RunPython(create_index_facilities_by_procedure, drop_index_facilities_by_procedure),
    ]
