# Generated by Django 3.2.4 on 2023-08-02 23:00

from django.db import connection
from django.db import migrations

query = (
    'DELETE FROM api_facilityindex '
    'WHERE id not in (SELECT id from api_facility);'
)


def delete_index_of_deleted_facilities(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(query)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_index_facilities'),
    ]

    operations = [migrations.RunPython(delete_index_of_deleted_facilities)]
