# Generated by Django 3.2.4 on 2023-08-03 15:00

import os

from django.db import connection
from django.db import migrations


def run_sql_file(file_name):
    file_path = os.path.join('./sqls/', file_name)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


def create_index_facilities_by_procedure(apps, schema_editor):
    run_sql_file('index_facilities_by2.sql')


def drop_index_facilities_by_procedure(apps, schema_editor):
    run_sql_file('index_facilities_by.sql')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_delete_index_of_deleted_facilities'),
    ]

    operations = [
        migrations.RunPython(
            create_index_facilities_by_procedure,
            drop_index_facilities_by_procedure,
        ),
    ]
