# Generated by Django 3.2.4 on 2023-08-17 14:10

import os

from django.db import connection
from django.db import migrations


def run_sql_file(file_name):
    file_path = os.path.join('./sqls/', file_name)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


def run_sql_files(file_list):
    for file_name in file_list:
        run_sql_file(file_name)


def create_index_facilities_by_procedure(apps, schema_editor):
    run_sql_files([
        'index_facilities2.sql',
        'index_facilities_by3.sql',
    ])


def drop_index_facilities_by_procedure(apps, schema_editor):
    run_sql_files([
        'index_facilities.sql',
        'index_facilities_by2.sql',
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_index_facilities2'),
    ]

    operations = [
        migrations.RunPython(
            create_index_facilities_by_procedure,
            drop_index_facilities_by_procedure,
        ),
    ]
