# Generated by Django 3.2.4 on 2023-08-17 14:10

import os

from django.db import connection
from django.db import migrations


def run_sql_file(file_name):
    file_path = os.path.join('./sqls/', file_name)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


def run_sql_files(file_list):
    for file_name in file_list:
        run_sql_file(file_name)


def create_new_procedures(apps, schema_editor):
    run_sql_files([
        'format_numbers_of_workers_0119.sql',
        'index_facilities_0119.sql',
        'index_facilities_by_0119.sql',
    ])

def drop_new_procedures(apps, schema_editor):
    run_sql_files([
        'index_facilities2.sql',
        'index_facilities_by3.sql',
        'format_numbers_of_workers.sql',
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_index_facilities_by'),
    ]

    operations = [
        migrations.RunPython(
            create_new_procedures,
            drop_new_procedures,
        ),
    ]
