# Generated by Django 3.2.4 on 2023-09-15 09:51

import os

import django.contrib.postgres.fields
from django.db import migrations, models, connection
from django.contrib.postgres.operations import UnaccentExtension
from django.db.migrations.state import StateApps
from django.contrib.gis.db.backends.postgis.schema import PostGISSchemaEditor

def update_indexing_procedures(
        apps: StateApps, schema_editor: PostGISSchemaEditor) -> None:
    # Add the custom_text_search column to the indexing procedures.
    run_sql_files([
        '0121_index_facilities.sql',
        '0121_index_facilities_by.sql',
    ])


def drop_indexing_procedures_update(
        apps: StateApps, schema_editor: PostGISSchemaEditor) -> None:
    run_sql_files([
        '0120_index_facilities.sql',
        '0120_index_facilities_by.sql',
    ])


def run_sql_files(file_list: list) -> None:
    for file_name in file_list:
        run_sql_file(file_name)


def run_sql_file(file_name: str) -> None:
    file_path = os.path.join('./sqls/', file_name)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_new_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityindex',
            name='custom_text_search',
            field=models.TextField(default='', help_text='A concatenated string of custom values for searching the facility in accent-insensitive and accent-sensitive lookup modes.'),
        ),
        migrations.AlterField(
            model_name='facilityindex',
            name='approved_claim_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(db_index=True, default=list, editable=False, help_text='The related approved claim facilities.', null=True), size=None),
        ),
        migrations.AlterField(
            model_name='facilityindex',
            name='facility_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=list, help_text='List of facility names for given facility.'), size=None),
        ),
        UnaccentExtension(),  # Activate unaccent extension.
        migrations.RunPython(
            update_indexing_procedures,
            drop_indexing_procedures_update
        )
    ]
