# Generated by Django 3.2.4 on 2023-09-04 14:17

from django.db import connection
from django.db.migrations import Migration, CreateModel, RunPython
from django.db.models import (
    BigAutoField,
    ForeignKey,
    CharField,
    Index,
    JSONField,
    IntegerField,
    DateTimeField,
    CASCADE,
)

from api.models.facility.facility_list_item import FacilityListItem
from api.models.facility.field_type import FieldType
from api.migrations._migration_helper import MigrationHelper

h = MigrationHelper(connection)

common_fields = [
    ('id', BigAutoField(auto_created=True, primary_key=True, serialize=False)),
    ('key', CharField(
        max_length=200, null=False, blank=False,
        help_text='Name of the field for facility list item.')),
    ('value', JSONField(
        null=False, blank=False,
        help_text='Content of the field for facility list item.')),
    ('type', IntegerField(choices=FieldType.choices)),
    ('updated_at', DateTimeField(auto_now=True)),
    ('created_at', DateTimeField(auto_now_add=True)),
]

facility = ('facility', ForeignKey(
    to='Facility', null=False, on_delete=CASCADE,
    help_text='The facility which this field belongs to.'
))

facility_list_item = ('facility_list_item', ForeignKey(
    to='FacilityListItem', null=False, on_delete=CASCADE,
    help_text='The facility list item, which this field belongs to.'
))
# CASCADE on deletion of Parent deletes its Children (fields)


def create_new_procedures(apps, schema_editor):
    h.run_sql_files([
        '0122_index_custom_text.sql',
        '0122_index_facilities.sql',
        '0122_index_facilities_by.sql',
    ])


def drop_new_procedures(apps, schema_editor):
    h.run_sql_files([
        '0121_index_facilities.sql',
        '0121_index_facilities_by.sql',
    ])
    h.drop_function('index_custom_text(text)')


def reindex_facility_list_items(apps, schema_editor):
    [
        index_custom_text(facility_list_item)
        for facility_list_item
        in FacilityListItem.objects.all().iterator()
    ]


class Migration(Migration):
    dependencies = [('api', '0121_introduce_unaccent_search')]
    operations = [
        CreateModel(
            name='FacilityField',
            fields=[*common_fields, facility],
            options={
                 'unique_together': [['facility_id', 'key']],
                 'indexes': [
                     Index(
                         fields=['facility_id', 'key'],
                         name='facility_id_key_idx'
                     ),
                 ]
             },
        ),
        CreateModel(
            name='FacilityListItemField',
            fields=[*common_fields, facility_list_item],
            options={
                 'unique_together': [['facility_list_item_id', 'key']],
                 'indexes': [
                     Index(
                         fields=['facility_list_item_id', 'key'],
                         name='facility_list_item_id_key_idx'
                     ),
                 ]
             },
        ),
        # RunPython(create_new_procedures, drop_new_procedures),
        # RunPython(reindex_facility_list_items)
    ]
