# Generated by Django 3.2.4 on 2023-09-04 14:17

from django.db import connection
from django.db.migrations import Migration, RunPython

from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def update_indexing_procedure(apps, schema_editor):
    helper.run_sql_files([
        '0123_index_facilities.sql',
        '0123_index_facilities_by.sql',
    ])


def drop_update(apps, schema_editor):
    helper.run_sql_files([
        '0122_index_facilities.sql',
        '0122_index_facilities_by.sql',
    ])


class Migration(Migration):
    dependencies = [('api', '0122_add_fields_to_af_and_afli')]
    operations = [
        RunPython(update_indexing_procedure, drop_update),
    ]
