# Generated by Django 3.2.4 on 2023-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_facility_index_gin_index'),
        ('api', '0131_introduce_sql_triggers_instead_of_django_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderation_mode',
            field=models.BooleanField(default=False, help_text='The ability to activate the Moderation features mode.', verbose_name='moderation mode'),
        ),
    ]
