# Generated by Django 3.2.4 on 2023-11-30 14:47

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import models
from django.db.migrations import Migration, CreateModel, RunPython

from api.models.dynamic_setting import DynamicSetting


def add_default_dynamic_settings(apps, schema_editor):
    dynamic_settings = DynamicSetting()
    dynamic_settings.save()


class Migration(Migration):

    dependencies = [
        ('api', '0132_add_moderation_mode_field'),
    ]

    operations = [
        CreateModel(
            name='TileCache',
            fields=[
                ('path', models.TextField(help_text='The requested tile URL.', primary_key=True, serialize=False)),
                ('embed', models.BooleanField(default=False, help_text='Whether the tile is generated for an embedded map.')),
                ('contributors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(help_text='The ID of the contributor passed via query param.'), default=list, size=None)),
                ('value', models.BinaryField(help_text='The cached binary tile.')),
                ('counter', models.IntegerField(default=0, help_text='The count of the number of times the cached tile was used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        CreateModel(
            name='DynamicSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_tile_expiration_time', models.IntegerField(default=604800, help_text='The expiration time in seconds for the cached tile.')),
            ],
        ),
        RunPython(add_default_dynamic_settings, RunPython.noop),
    ]
