# Generated by Django 3.2.4 on 2024-02-12 12:59

from django.db import connection
from django.db.migrations import Migration, RunPython

from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def update_indexing_functions(apps, schema_editor):
    '''
    This function replaces the old index_activity_reports_info and
    index_approved_claim functions with similar ones that do not
    index emails.
    '''

    helper.run_sql_files([
        '0136_index_activity_reports_info.sql',
        '0136_index_approved_claim.sql'
        ])


def revert_updating_indexing_functions(apps, schema_editor):
    helper.run_sql_files([
        '0130_index_activity_reports_info.sql',
        '0130_index_approved_claim.sql'
        ])


class Migration(Migration):

    dependencies = [
        ('api', '0135_disable_duplicates_and_lowercase_all_emails'),
    ]

    operations = [
        RunPython(update_indexing_functions,
                  revert_updating_indexing_functions)
    ]
