# Generated by Django 3.2.4 on 2024-02-12 12:59

from django.db import connection
from django.db.migrations import Migration, RunPython

from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def introduce_updated_index_activity_reports_info(apps, schema_editor):
    helper.run_sql_files(['0136_index_activity_reports_info.sql'])


def revert_updated_index_activity_reports_info(apps, schema_editor):
    helper.run_sql_files(['0130_index_activity_reports_info.sql'])


class Migration(Migration):

    dependencies = [
        ('api', '0135_disable_duplicates_and_lowercase_all_emails'),
    ]

    operations = [
        RunPython(introduce_updated_index_activity_reports_info,
                  revert_updated_index_activity_reports_info)
    ]
