# Generated by Django 3.2.4 on 2024-03-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_remove_indexing_ppe_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContributorWebhook',
        ),
    ]
