# Generated by Django 3.2.4 on 2024-03-15 11:46

from django.db import migrations


class Migration(migrations.Migration):
    def create_list_upload_endpoint_switcher(apps, schema_editor):
        Switch = apps.get_model('waffle', 'Switch')
        Switch.objects.create(name='use_old_upload_list_endpoint',
                              active=False)

    def delete_list_upload_endpoint_switcher(apps, schema_editor):
        Switch = apps.get_model('waffle', 'Switch')
        Switch.objects.get(name='use_old_upload_list_endpoint').delete()

    dependencies = [
        ('api', '0141_delete_contributor_webhooks'),
    ]

    operations = [
        migrations.RunPython(
            create_list_upload_endpoint_switcher,
            delete_list_upload_endpoint_switcher
        )
    ]
