# Generated by Django 3.2.4 on 2024-04-12 09:58

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_introduce_temporary_endpoint_switcher_for_list_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityClaimAttachmentURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('claim_attachment_url', models.URLField(blank=True, help_text='AWS S3 URL linking to a claimant attached file.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='facilityclaimattachmenturls',
            name='claim',
            field=models.ForeignKey(help_text='The facility claim for this attachment file.', on_delete=django.db.models.deletion.PROTECT, to='api.facilityclaim'),
        ),
    ]
