# Generated by Django 3.2.4 on 2024-04-17 05:25

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_introduce_temporary_endpoint_switcher_for_list_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityClaimAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('file_name', models.CharField(editable=False, help_text='The full name of the uploaded claimant attached file.', max_length=200)),
                ('claim_attachment', models.FileField(blank=True, help_text='The uploaded claimant attached file.', null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='facilityclaimattachments',
            name='claim',
            field=models.ForeignKey(help_text='The facility claim for this attachment file.', on_delete=django.db.models.deletion.PROTECT, to='api.facilityclaim'),
        ),
    ]
