# Generated by Django 3.2.4 on 2024-04-22 13:48

from django.db.migrations import RemoveField, Migration


class Migration(Migration):
    '''
    Since email and preferred_contact_method are no longer necessary for the
    claim form, they should be deleted from the FacilityClaim model and the
    respective history table.
    '''

    dependencies = [
        ('api', '0142_introduce_temporary_endpoint_switcher_for_list_uploads'),
    ]

    operations = [
        RemoveField(
            model_name='facilityclaim',
            name='email',
        ),
        RemoveField(
            model_name='facilityclaim',
            name='preferred_contact_method',
        ),
        RemoveField(
            model_name='historicalfacilityclaim',
            name='email',
        ),
        RemoveField(
            model_name='historicalfacilityclaim',
            name='preferred_contact_method',
        )
    ]
