# Generated by Django 3.2.4 on 2024-04-22 13:48

from django.db import connection
from django.db.migrations import RemoveField, Migration, RunPython

from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def update_indexing_function(apps, schema_editor):
    '''
    This function replaces the old index_approved_claim function with a
    similar one that does not index preferred_contact_method field.
    '''

    helper.run_sql_files(['0143_index_approved_claim.sql'])


class Migration(Migration):
    '''
    Since email and preferred_contact_method are no longer necessary for the
    claim form, they should be deleted from the FacilityClaim model and the
    respective history table.
    '''

    dependencies = [
        ('api', '0142_introduce_temporary_endpoint_switcher_for_list_uploads'),
    ]

    operations = [
        RunPython(update_indexing_function),
        RemoveField(
            model_name='facilityclaim',
            name='email',
        ),
        RemoveField(
            model_name='facilityclaim',
            name='preferred_contact_method',
        ),
        RemoveField(
            model_name='historicalfacilityclaim',
            name='email',
        ),
        RemoveField(
            model_name='historicalfacilityclaim',
            name='preferred_contact_method',
        )
    ]
