# Generated by Django 3.2.4 on 2024-06-25 07:28

from django.db import connection
from django.db.migrations import Migration, RunPython

from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def introduce_function_formatting_number_to_percent(apps, schema_editor):
    helper.run_sql_files([
        '0150_drop_calc_column_func.sql',
        '0150_add_percent_to_number.sql',
    ])


def revert_function_formatting_number_to_percent(apps, schema_editor):
    helper.run_sql_files([
        '0150_revert_add_percent_to_number.sql',
    ])


class Migration(Migration):
    dependencies = [('api', '0149_rename_facility_workers_count_new_to_facility_workers_count')]
    operations = [
        RunPython(introduce_function_formatting_number_to_percent,
                  revert_function_formatting_number_to_percent)
    ]
