
# Generated by Django 3.2.4 on 2024-07-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_replace_index_number_of_workers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicSetting',
        ),
        migrations.DeleteModel(
            name='TileCache',
        ),
    ]
