# Generated by Django 3.2.17 on 2024-10-14 10:04

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_delete_endpoint_switcher_for_list_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the moderation queue entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when the moderation queue entry was last updated.')),
                ('moderation_decision_date', models.DateTimeField(auto_now=True, help_text='Date when the moderation decision was made.')),
                ('raw_json', models.JSONField(default=dict, help_text='Key-value pairs of the parsed row and header for the moderation data.')),
                ('match_status', models.CharField(choices=[('MATCHED', 'Matched'), ('NEW_LOCATION', 'New Location'), ('POTENTIAL_MATCH', 'Potential Match')], help_text='Match status of the production location.', max_length=200, null=True)),
                ('moderation_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', help_text='Moderation status of the production location.', max_length=200)),
                ('record_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, help_text='List of record types for the production location.', size=None)),
            ],
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='production_location_list_item',
            field=models.OneToOneField(help_text='Linked facility list item for this moderation queue entry.', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_queue', to='api.facilitylistitem'),
        ),
    ]
