# Generated by Django 3.2.17 on 2024-11-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_create_moderation_event_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Moderation status of the production location.', max_length=8),
        ),
    ]
