# Generated by Django 3.2.17 on 2024-11-13 13:59
from django.db import migrations


def create_disable_list_uploading_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(name='disable_list_uploading', active=False)


def delete_disable_list_uploading_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.get(name='disable_list_uploading').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_create_moderation_event_table'),
    ]

    operations = [
        migrations.RunPython(
            create_disable_list_uploading_switch,
            delete_disable_list_uploading_switch,)
    ]
