# Generated by Django 3.2.17 on 2024-11-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_alter_status_of_moderation_event_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitylist',
            name='parsing_errors',
            field=models.JSONField(blank=True, default=list, help_text='List-level and internal errors logged during background parsing of the list.', null=True),
        ),
    ]
