# Generated by Django 3.2.17 on 2025-01-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_refresh_pg_statistic_and_upgrade_postgres_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationevent',
            name='action_type',
            field=models.CharField(blank=True, choices=[('NEW_LOCATION', 'New Location'), ('MATCHED', 'Matched'), ('REJECTED', 'Rejected')], null=True, help_text='Type of moderation action.', max_length=12),
        ),
    ]
