# Generated by Django 3.2.17 on 2025-02-04 13:35

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_add_moderationevent_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationevent',
            name='action_perform_by',
            field=models.OneToOneField(help_text='Linked user id who performed the action.', null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_event_action_perform_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
