# Generated by Django 3.2.17 on 2025-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_add_moderationevent_action_perform_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationevent',
            name='action_reason_text_cleaned',
            field=models.TextField(
                blank=True,
                help_text='Cleaned version of the action reason text.',
            ),
        ),
        migrations.AddField(
            model_name='moderationevent',
            name='action_reason_text_raw',
            field=models.TextField(
                blank=True,
                help_text='Raw version of the action reason text.',
            ),
        ),
    ]
