# Generated by Django 3.2.17 on 2025-03-20 17:42

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_add_moderationevent_action_reason_text_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDownloadLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('last_download_time', models.DateTimeField(blank=True, help_text='The date of the last download.', null=True)),
                ('allowed_downloads', models.PositiveIntegerField(default=10, help_text='The number of facility data downloads a user can make per month.')),
                ('allowed_records_number', models.PositiveIntegerField(default=1000, help_text='The maximum number of facility records a user can download in a single request.')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='The number of facility data downloads a user has already made in the current month.')),
            ],
        ),
        migrations.AddField(
            model_name='facilitydownloadlimit',
            name='user',
            field=models.OneToOneField(help_text='The user to whom the download limit applies.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
