# Generated by Django 3.2.17 on 2025-03-19 11:59

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_add_moderationevent_action_reason_text_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDownloadLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('last_download_time', models.DateTimeField(blank=True, help_text='The date of the last download.', null=True)),
                ('allowed_downloads', models.PositiveIntegerField(default=10, help_text='The number of facility data downloads a user can make per month.')),
                ('allowed_records_number', models.PositiveIntegerField(default=1000, help_text='The number of facility records for a user can be made in a single download.')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='The number of facility data downloads a user has already made in the current month.')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFacilityDownloadLimit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True)),
                ('last_download_time', models.DateTimeField(blank=True, help_text='The date of the last download.', null=True)),
                ('allowed_downloads', models.PositiveIntegerField(default=10, help_text='The number of facility data downloads a user can make per month.')),
                ('allowed_records_number', models.PositiveIntegerField(default=1000, help_text='The number of facility records for a user can be made in a single download.')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='The number of facility data downloads a user has already made in the current month.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical facility download limit',
                'verbose_name_plural': 'historical facility download limits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalfacilitydownloadlimit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfacilitydownloadlimit',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user to whom the download limit applies.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitydownloadlimit',
            name='user',
            field=models.OneToOneField(help_text='The user to whom the download limit applies.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
