# Generated by Django 3.2.17 on 2025-04-18 14:00

from django.db import migrations


class Migration(migrations.Migration):
    def create_show_additional_identifiers_switch(apps, schema_editor):
        Switch = apps.get_model('waffle', 'Switch')
        Switch.objects.create(name='show_additional_identifiers',
                              active=False)

    def delete_show_additional_identifiers_switch(apps, schema_editor):
        Switch = apps.get_model('waffle', 'Switch')
        Switch.objects.get(name='show_additional_identifiers').delete()

    dependencies = [
        ('api', '0168_introduce_a_switch_to_block_location_downloads'),
    ]

    operations = [
        migrations.RunPython(
            create_show_additional_identifiers_switch,
            delete_show_additional_identifiers_switch
        )
    ]
