# Generated by Django 3.2.17 on 2025-06-02 12:00

from django.db import connection, migrations, models
from django.db.migrations import RunPython
from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def update_indexing_functions(apps, schema_editor):
    '''
    This function replaces the old index_facilities and
    index_facilities_by functions with similar ones that
    index origin_source field.
    '''

    helper.run_sql_files([
        '0170_index_facilities.sql',
        '0170_index_facilities_by.sql'
        ])


def revert_updating_indexing_functions(apps, schema_editor):
    '''
    This function reverts the changes made by update_indexing_functions
    by running the SQL files for the previous version of indexing functions.
    '''
    helper.run_sql_files([
        '0140_index_facilities.sql',
        '0140_index_facilities_by.sql'
        ])


def introduce_sql_triggers(apps, schema_editor):
    """
    Introduce SQL triggers for origin_source field.
    """
    helper.run_sql_files(['0170_create_origin_source_triggers.sql'])


def revert_sql_triggers(apps, schema_editor):
    helper.run_sql_files(['0170_revert_origin_source_triggers.sql'])


def create_origin_source_function(apps, schema_editor):
    '''
    This function create the set_origin_source function
    to used by the triggers.
    '''

    helper.run_sql_files(['0170_set_origin_source.sql'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_introduce_show_additional_identifiers_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_contributor
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='extendedfield',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_extendedfield
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='facility',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_facility
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='facilityactivityreport',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_facilityactivityreport
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='facilityalias',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_facilityalias
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='facilityclaim',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_facilityclaim
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='facilitylist',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_facilitylist
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='facilitylistitem',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_facilitylistitem
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='facilitymatch',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_facilitymatch
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='source',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_source
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='facilityindex',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_facilityindex
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='facilitylocation',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_facilitylocation
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='user',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_user
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='historicalcontributor',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', ' OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                help_text='The environment value where instance running',
                max_length=200
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_historicalcontributor
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='historicalextendedfield',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', ' OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                help_text='The environment value where instance running',
                max_length=200
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_historicalextendedfield
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='historicalfacility',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', ' OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                help_text='The environment value where instance running',
                max_length=200
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_historicalfacility
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='historicalfacilityactivityreport',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', ' OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                help_text='The environment value where instance running',
                max_length=200
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_historicalfacilityactivityreport
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='historicalfacilityalias',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', ' OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                help_text='The environment value where instance running',
                max_length=200
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_historicalfacilityalias
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', ' OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                help_text='The environment value where instance running',
                max_length=200
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_historicalfacilityclaim
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddField(
            model_name='historicalfacilitymatch',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', ' OS Hub'), ('rba', 'RBA')],
                blank=True,
                null=True,
                help_text='The environment value where instance running',
                max_length=200
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE api_historicalfacilitymatch
                SET origin_source = 'os_hub'
                WHERE origin_source IS NULL OR origin_source = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        RunPython(update_indexing_functions,
                  revert_updating_indexing_functions),
        RunPython(create_origin_source_function),
        RunPython(introduce_sql_triggers,
                  revert_sql_triggers)
    ]
