# Generated by Django 3.2.17 on 2025-06-03 08:56

import api.models.facility_download_limit
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_introduce_show_additional_identifiers_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDownloadLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('free_download_records_limit', models.PositiveIntegerField(default=10000, help_text='The number of facilities a user can download per calendar year for free.')),
                ('paid_download_records_limit', models.PositiveIntegerField(default=0, help_text='The number of paid facilities that a user can download.')),
                ('remaining_free_records', models.PositiveIntegerField(default=0, help_text='The number of free facilities of the user has remaining in the current year.', verbose_name='Current remaining free records')),
                ('remaining_paid_records', models.PositiveIntegerField(default=0, help_text='The number of paid facilities of the user has remaining.', verbose_name='Current remaining paid records')),
                ('limit_update_date', models.DateTimeField(default=api.models.facility_download_limit.first_day_of_next_year, help_text='The date when the free limit should be updated.')),
            ],
        ),
        migrations.AddField(
            model_name='facilitydownloadlimit',
            name='user',
            field=models.OneToOneField(help_text='The user to whom the download limit applies.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
