# Generated by Django 3.2.17 on 2025-06-02 12:00

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_introduce_show_additional_identifiers_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                default='os_hub',
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.AddField(
            model_name='extendedfield',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                default='os_hub',
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.AddField(
            model_name='facility',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                default='os_hub',
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.AddField(
            model_name='facilityactivityreport',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                default='os_hub',
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
        migrations.AddField(
            model_name='facilityalias',
            name='origin_source',
            field=models.CharField(
                choices=[('os_hub', 'OS Hub'), ('rba', 'RBA')],
                default='os_hub',
                max_length=200,
                help_text="The environment value where instance running"
            ),
        ),
    ]
