# Generated by Django 3.2.17 on 2025-06-04 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import make_aware


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_introduce_show_additional_identifiers_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDownloadLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('free_download_records', models.PositiveIntegerField(default=10000, help_text='The number of facilities a user can download per calendar year for free.')),
                ('paid_download_records', models.PositiveIntegerField(default=0, help_text='The number of paid facilities that the user can download.')),
                ('updated_at', models.DateTimeField(default=lambda: make_aware(datetime(2025, 6, 28)), help_text='The date when the free limit was set or updated.')),
            ],
        ),
        migrations.AddField(
            model_name='facilitydownloadlimit',
            name='user',
            field=models.OneToOneField(help_text='The user to whom the download limit applies.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
