# Generated by Django 3.2.17 on 2025-06-23 16:39

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_added_origin_source_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDownloadLimit',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the facility download limit record.', primary_key=True, serialize=False, unique=True)),
                ('free_download_records', models.PositiveIntegerField(default=5000, help_text='The number of facilities the user can download per calendar year for free.')),
                ('paid_download_records', models.PositiveIntegerField(default=0, help_text='The number of paid facilities that the user can download.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date when the free limit was set or updated.')),
                ('purchase_date', models.DateTimeField(blank=True, help_text='The date when paid facility records were purchased.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='facilitydownloadlimit',
            name='user',
            field=models.OneToOneField(help_text='The user to whom the download limit applies.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
