# Generated by Django 3.2.17 on 2025-07-04 06:18

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_added_origin_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='created_from',
            field=models.OneToOneField(help_text='The original uploaded list item from which this facility was created.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_facility', to='api.facilitylistitem'),
        ),
    ]
