# Generated by Django 3.2.17 on 2025-07-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_added_origin_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='path',
            field=models.CharField(help_text='The requested resource path', max_length=4096),
        ),
    ]
