# Generated by Django 3.2.17 on 2025-06-23 12:00

from django.db import migrations


def create_private_instance_switch(apps, schema_editor):
    switch = apps.get_model('waffle', 'Switch')
    switch.objects.create(name='private_instance', active=False)


def delete_private_instance_switch(apps, schema_editor):
    switch = apps.get_model('waffle', 'Switch')
    switch.objects.get(name='private_instance').delete()

def delete_allow_large_downloads_switch(apps, schema_editor):
    switch = apps.get_model('waffle', 'Switch')
    switch.objects.get(name='allow_large_downloads').delete()

def create_allow_large_downloads_switch(apps, schema_editor):
    switch = apps.get_model('waffle', 'Switch')
    switch.objects.create(name='allow_large_downloads', active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_create_download_location_success_payment_table'),
    ]

    operations = [
        migrations.RunPython(
            create_private_instance_switch,
            delete_private_instance_switch),
        
        migrations.RunPython(
            delete_allow_large_downloads_switch,
            create_allow_large_downloads_switch)
    ]
