# Generated by Django 3.2.17 on 2025-09-02 08:43

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_introduce_enable_dromo_uploading_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_partially_update_production_location',
            field=models.BooleanField(default=False, help_text='User can omit name, address and country fields while updating production location by OS ID (only for verified contributors)'),
        ),
    ]
