# Generated by Django 3.2.17 on 2025-08-11 07:06

from django.db import migrations, models


def create_disable_list_uploading_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.create(name='enable_record_linkage', active=False)


def delete_disable_list_uploading_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.get(name='enable_record_linkage').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_introduce_enable_dromo_uploading_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, help_text='Name of the machine learning configuration.', unique=True)),
                ('description', models.CharField(max_length=255, help_text='Description of the machine learning configuration.')),
                ('value', models.CharField(max_length=255, help_text='Value of the machine learning configuration.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the moderation queue entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date when the moderation queue entry was last updated.')),
            ],
        ),
        migrations.RunPython(
            create_disable_list_uploading_switch,
            delete_disable_list_uploading_switch,
        ),
    ]