# Generated by Django 3.2.17 on 2025-07-24 13:49

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_introduce_enable_dromo_uploading_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trusted',
            field=models.BooleanField(default=False, help_text='Designates whether this user is trusted to PATCH production locations.', verbose_name='trusted'),
        ),
    ]
