# Generated by Django 3.2.17 on 2025-08-12 13:21
from django.db import migrations, models


def create_enable_record_linkage_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.update_or_create(
        name='enable_record_linkage',
        defaults={'active': False},
    )


def delete_enable_record_linkage_switch(apps, schema_editor):
    Switch = apps.get_model('waffle', 'Switch')
    Switch.objects.filter(name='enable_record_linkage').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_introduce_enable_dromo_uploading_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the setting.', max_length=255, unique=True)),
                ('description', models.CharField(help_text='Description of the setting.', max_length=255)),
                ('value', models.CharField(help_text='Value of the setting.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the setting was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date when the setting was last updated.')),
            ],
        ),
        migrations.RunPython(
            create_enable_record_linkage_switch,
            delete_enable_record_linkage_switch,
        ),
    ]
