# Generated by Django 3.2.17 on 2025-08-16 

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_add_campaign_code_to_facility_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The reason text to display in the dropdown', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reason should appear in the dropdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Claims Reason',
                'verbose_name_plural': 'Claims Reasons',
                'ordering': ['text'],
            },
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='claim_reason',
            field=models.CharField(blank=True, help_text='The reason why the organization is claiming this facility', max_length=100, null=True, verbose_name='claim reason'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='claim_reason',
            field=models.CharField(blank=True, help_text='The reason why the organization is claiming this facility', max_length=100, null=True, verbose_name='claim reason'),
        ),
    ]