# Generated by Django 3.2.17 on 2025-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_add_label_to_partner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityclaim',
            name='closing_date',
            field=models.DateField(blank=True, help_text='The closing date of the location for emissions estimation', null=True, verbose_name='closing date'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='energy_animal_waste',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual animal waste energy consumption in Joules', null=True, verbose_name='energy animal waste consumption'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='energy_biomass',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual biomass energy consumption in Joules', null=True, verbose_name='energy biomass consumption'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='energy_charcoal',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual charcoal energy consumption in Joules', null=True, verbose_name='energy charcoal consumption'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='energy_coal',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual coal energy consumption in Joules', null=True, verbose_name='energy coal consumption'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='energy_diesel',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual diesel energy consumption in Joules', null=True, verbose_name='energy diesel consumption'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='energy_electricity',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual electricity consumption in MWh', null=True, verbose_name='energy electricity consumption'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='energy_kerosene',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual kerosene energy consumption in Joules', null=True, verbose_name='energy kerosene consumption'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='energy_natural_gas',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual natural gas energy consumption in Joules', null=True, verbose_name='energy natural gas consumption'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='energy_other',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual other energy source consumption in Joules', null=True, verbose_name='energy other consumption'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='estimated_annual_throughput',
            field=models.PositiveBigIntegerField(blank=True, help_text='The estimated annual throughput in kg/year', null=True, verbose_name='estimated annual throughput'),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='opening_date',
            field=models.DateField(blank=True, help_text='The opening date of the location for emissions estimation', null=True, verbose_name='opening date'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='closing_date',
            field=models.DateField(blank=True, help_text='The closing date of the location for emissions estimation', null=True, verbose_name='closing date'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='energy_animal_waste',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual animal waste energy consumption in Joules', null=True, verbose_name='energy animal waste consumption'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='energy_biomass',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual biomass energy consumption in Joules', null=True, verbose_name='energy biomass consumption'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='energy_charcoal',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual charcoal energy consumption in Joules', null=True, verbose_name='energy charcoal consumption'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='energy_coal',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual coal energy consumption in Joules', null=True, verbose_name='energy coal consumption'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='energy_diesel',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual diesel energy consumption in Joules', null=True, verbose_name='energy diesel consumption'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='energy_electricity',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual electricity consumption in MWh', null=True, verbose_name='energy electricity consumption'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='energy_kerosene',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual kerosene energy consumption in Joules', null=True, verbose_name='energy kerosene consumption'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='energy_natural_gas',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual natural gas energy consumption in Joules', null=True, verbose_name='energy natural gas consumption'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='energy_other',
            field=models.PositiveBigIntegerField(blank=True, help_text='Annual other energy source consumption in Joules', null=True, verbose_name='energy other consumption'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='estimated_annual_throughput',
            field=models.PositiveBigIntegerField(blank=True, help_text='The estimated annual throughput in kg/year', null=True, verbose_name='estimated annual throughput'),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='opening_date',
            field=models.DateField(blank=True, help_text='The opening date of the location for emissions estimation', null=True, verbose_name='opening date'),
        )
    ]
