# Generated by Django 3.2.17 on 2025-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_introduce_free_emissions_estimate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityclaim',
            name='claimant_employment_verification_method',
            field=models.CharField(
                blank=True,
                help_text="Claimant's employment verification method.",
                max_length=250,
                null=True,
                verbose_name='claimant employment verification method',
            ),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='claimant_linkedin_profile_url',
            field=models.URLField(
                blank=True,
                help_text="Claimant's LinkedIn profile URL.",
                null=True,
                verbose_name='claimant linkedin profile url'
            ),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='claimant_location_relationship',
            field=models.CharField(
                blank=True,
                help_text="Claimant's relationship to the location of the production location.",
                max_length=250,
                null=True,
                verbose_name='claimant location relationship'
            ),
        ),
        migrations.AddField(
            model_name='facilityclaim',
            name='location_address_verification_method',
            field=models.CharField(
                blank=True,
                help_text="Verification method used to confirm the production location's address.",
                max_length=250,
                null=True,
                verbose_name='location address verification method',
            ),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='claimant_employment_verification_method',
            field=models.CharField(
                blank=True,
                help_text="Claimant's employment verification method.",
                max_length=250,
                null=True,
                verbose_name='claimant employment verification method',
            ),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='claimant_linkedin_profile_url',
            field=models.URLField(
                blank=True,
                help_text="Claimant's LinkedIn profile URL.",
                null=True,
                verbose_name='claimant linkedin profile url'
            ),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='claimant_location_relationship',
            field=models.CharField(
                blank=True,
                help_text="Claimant's relationship to the location of the production location.",
                max_length=250,
                null=True,
                verbose_name='claimant location relationship'
            ),
        ),
        migrations.AddField(
            model_name='historicalfacilityclaim',
            name='location_address_verification_method',
            field=models.CharField(
                blank=True,
                help_text="Verification method used to confirm the production location's address.",
                max_length=250,
                null=True,
                verbose_name='location address verification method',
            ),
        ),
    ]
