# Generated by Django 3.2.17 on 2025-11-07 12:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_add_claim_fields_for_new_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityclaim',
            name='facility_type',
            field=models.CharField(blank=True, help_text='The editable facility type for this claim.', max_length=300, null=True, verbose_name='facility type'),
        ),
        migrations.AlterField(
            model_name='historicalfacilityclaim',
            name='facility_type',
            field=models.CharField(blank=True, help_text='The editable facility type for this claim.', max_length=300, null=True, verbose_name='facility type'),
        ),
    ]
