# Generated by Django 3.2.17 on 2025-11-04 11:47

from django.db import migrations
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_add_claim_fields_for_new_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfield',
            name='source_by',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]

