# Generated by Django 3.2.17 on 2025-11-04 11:47

from django.db import migrations
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_remove_facilityclaim_facility_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfield',
            name='source_by',
            field=ckeditor.fields.RichTextField(blank=True, null=True, config_name='default'),
        ),
    ]

