# Generated by Django 3.2.17 on 2025-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_add_source_by_to_partner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfield',
            name='json_schema',
            field=models.JSONField(blank=True, null=True, help_text='JSON Schema for validating object type partner fields. Used when type is "object".'),
        ),
    ]

