# Generated by Django 3.2.17 on 2025-11-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_add_json_schema_to_partner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfield',
            name='base_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='partnerfield',
            name='display_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
