# Generated by Django 3.2.17 on 2025-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_add_json_schema_to_partner_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='partner_fields',
            field=models.ManyToManyField(blank=True, help_text='Partner fields that this contributor can access', to='api.PartnerField'),
        ),
    ]
