# Generated by Django 3.2.17 on 2025-11-25 15:46

from django.db.migrations import Migration, RunPython
from django.db import connection


from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def update_indexing_function(apps, schema_editor):
    '''
    This function replaces the old index_claim_info function with a similar
    one that indexes new operational and environmental data from the location
    claim.
    '''

    helper.run_sql_files([
        '0188_index_claim_info.sql'
    ])


def revert_updating_indexing_function(apps, schema_editor):
    helper.run_sql_files([
        '0130_index_claim_info.sql'
    ])


class Migration(Migration):

    dependencies = [
        ('api', '0187_remove_null_from_contributor_partner_fields'),
    ]

    operations = [
        RunPython(update_indexing_function,
                  revert_updating_indexing_function)
    ]
