# Generated by Django 3.2.17 on 2025-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_introduce_indexing_for_new_operational_and_environmental_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfield',
            name='base_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='partnerfield',
            name='display_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
