# Generated by Django 3.2.17 on 2025-12-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_add_base_url_and_text_field_to_partner_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageIndicatorCountryData',
            fields=[
                ('country_code', models.CharField(
                    help_text=(
                        'ISO 3166-1 alpha-2 country code '
                        '(e.g., US, GB, CN).'
                    ),
                    max_length=2,
                    primary_key=True,
                    serialize=False
                )),
                ('living_wage_link_national', models.URLField(
                    help_text=(
                        'Living wage benchmark link in national language.'
                    ),
                    max_length=500
                )),
                ('minimum_wage_link_english', models.URLField(
                    help_text='Minimum wage information link in English.',
                    max_length=500
                )),
                ('minimum_wage_link_national', models.URLField(
                    help_text=(
                        'Minimum wage information link in national language.'
                    ),
                    max_length=500
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wage Indicator Country Data',
                'verbose_name_plural': 'Wage Indicator Country Data',
            },
        ),
    ]
