# Generated by Django 3.2.17 on 2025-12-17 10:51

from django.db.migrations import Migration, AddField
from django.db.models import BooleanField


class Migration(Migration):

    dependencies = [
        ('api', '0189_add_base_url_and_text_field_to_partner_field'),
    ]

    operations = [
        AddField(
            model_name='partnerfield',
            name='active',
            field=BooleanField(
                default=True,
                help_text=(
                    'Indicates if this partner field is active. '
                    'Inactive fields are not available for contributions and '
                    'will not appear in listings.'
                ),
            ),
        ),
        AddField(
            model_name='partnerfield',
            name='system_field',
            field=BooleanField(
                default=False,
                help_text=(
                    'Indicates if this is a system field. '
                    'System fields cannot be deleted and have restricted '
                    'editing.'
                ),
            ),
        ),
    ]
