# Generated by Django 3.2.17 on 2025-12-16 13:36

from django.db.migrations import Migration, CreateModel
from django.db.models import URLField, DateTimeField, CharField


class Migration(Migration):

    dependencies = [
        ('api', '0189_add_base_url_and_text_field_to_partner_field'),
    ]

    operations = [
        CreateModel(
            name='WageIndicatorCountryData',
            fields=[
                (
                    'country_code',
                    CharField(
                        help_text=(
                            'ISO 3166-1 alpha-2 country code '
                            '(e.g., US, GB, CN).'
                        ),
                        max_length=2,
                        primary_key=True,
                        serialize=False
                    )
                ),
                (
                    'living_wage_link_national',
                    URLField(
                        help_text=(
                            'Living wage benchmark link in national '
                            'language.'
                        ),
                        max_length=500
                    )
                ),
                (
                    'minimum_wage_link_english',
                    URLField(
                        help_text=(
                            'Minimum wage information link in English.'
                        ),
                        max_length=500
                    )
                ),
                (
                    'minimum_wage_link_national',
                    URLField(
                        help_text=(
                            'Minimum wage information link in national '
                            'language.'
                        ),
                        max_length=500
                    )
                ),
                ('created_at', DateTimeField(auto_now_add=True)),
                ('updated_at', DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wage Indicator - Country Data',
                'verbose_name_plural': 'Wage Indicator - Country Data',
            },
        ),
        CreateModel(
            name='WageIndicatorLinkTextConfig',
            fields=[
                (
                    'link_type',
                    CharField(
                        choices=[
                            (
                                'living_wage_link_national',
                                'Living Wage Link National'
                            ),
                            (
                                'minimum_wage_link_english',
                                'Minimum Wage Link English'
                            ),
                            (
                                'minimum_wage_link_national',
                                'Minimum Wage Link National'
                            ),
                        ],
                        help_text=(
                            'Type of wage indicator link. The choices are '
                            'field names in the WageIndicatorCountryData '
                            'model. This field is a connector to relevant URL '
                            'field in the WageIndicatorCountryData model.'
                        ),
                        max_length=50,
                        primary_key=True,
                        serialize=False
                    )
                ),
                (
                    'display_text',
                    CharField(
                        help_text=(
                            'Display text to show for this link type. This is '
                            'the text that will be shown to the user when '
                            'they click on the wage indicator link of the '
                            'relevant type like living wage link national, '
                            'minimum wage link English, etc.'
                        ),
                        max_length=200
                    )
                ),
                ('created_at', DateTimeField(auto_now_add=True)),
                ('updated_at', DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wage Indicator - Link Text',
                'verbose_name_plural': 'Wage Indicator - Link Texts',
            },
        ),
    ]
