# Generated by Django 3.2.17 on 2025-12-17 11:19

from django.db.migrations import Migration, RunPython


def create_wage_indicator_partner_field(apps, schema_editor):
    '''Create wage_indicator partner field.'''
    PartnerField = apps.get_model('api', 'PartnerField')

    json_schema = {
        '$schema': 'https://json-schema.org/draft/2020-12/schema',
        'type': 'object',
        'title': 'Wage indicator reference links',
        'properties': {
            'living_wage_link_national': {
                'type': 'string',
                'format': 'uri',
                'title': 'Living wage reference link (national language)'
            },
            'minimum_wage_link_english': {
                'type': 'string',
                'format': 'uri',
                'title': 'Minimum wage reference link (English)'
            },
            'minimum_wage_link_national': {
                'type': 'string',
                'format': 'uri',
                'title': 'Minimum wage reference link (national language)'
            },
            'living_wage_link_national_text': {
                'type': 'string',
                'title': 'Living wage link text (national language)'
            },
            'minimum_wage_link_english_text': {
                'type': 'string',
                'title': 'Minimum wage link text (English)'
            },
            'minimum_wage_link_national_text': {
                'type': 'string',
                'title': 'Minimum wage link text (national language)'
            }
        }
    }

    source_by = (
        '<p>2024 Minimum Wage Benchmark sourced by '
        '<a href="https://wageindicator.org/" target="_blank" '
        'title="WageIndicator">WageIndicator</a></p>'
    )

    PartnerField.objects.create(
        name='wage_indicator',
        type='object',
        source_by=source_by,
        json_schema=json_schema,
        system_field=True
    )


def reverse_wage_indicator_partner_field(apps, schema_editor):
    '''Remove wage_indicator partner field.'''
    PartnerField = apps.get_model('api', 'PartnerField')
    PartnerField.objects.filter(name='wage_indicator').delete()


class Migration(Migration):

    dependencies = [
        ('api', '0190_add_active_system_field_to_partnerfield'),
    ]

    operations = [
        RunPython(
            create_wage_indicator_partner_field,
            reverse_wage_indicator_partner_field
        ),
    ]
