# Generated by Django 3.2.17 on 2025-12-16

import csv
import os
import sys
from django.db import migrations, models
from django.contrib.gis.db import models as gis_models
from django.contrib.gis.geos import GEOSGeometry, MultiPolygon

# Increase CSV field size limit to handle large geometry WKT strings
csv.field_size_limit(sys.maxsize)


def populate_tigerline_data(apps, schema_editor):
    '''
    Populate the USCountyTigerline table with data from CSV file.
    Geometry data is already in EPSG:5070 (Albers Equal Area).
    '''
    USCountyTigerline = apps.get_model('api', 'USCountyTigerline')

    base_dir = os.path.dirname(os.path.dirname(__file__))
    csv_path = os.path.join(base_dir, 'data', 'us_county_tigerline_2025.csv')

    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"CSV file not found at: {csv_path}. "
            "Please ensure the file exists."
        )

    tigerline_objects = []
    batch_size = 2000
    processed_count = 0
    error_count = 0

    with open(csv_path, 'r', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)

        for row_idx, row in enumerate(reader, start=1):
            geoid = row['geoid'].strip()
            name = row['name'].strip()
            geometry_wkt = row['geometry'].strip()

            if not geoid or not name or not geometry_wkt:
                error_count += 1
                continue

            try:
                # Parse geometry from WKT
                geom = GEOSGeometry(geometry_wkt, srid=5070)
                
                # Convert Polygon to MultiPolygon if needed
                if geom.geom_type == 'Polygon':
                    geom = MultiPolygon(geom, srid=5070)
                elif geom.geom_type != 'MultiPolygon':
                    raise ValueError(
                        f"Unexpected geometry type: {geom.geom_type}"
                    )

                tigerline_objects.append(
                    USCountyTigerline(
                        geoid=geoid,
                        name=name,
                        geometry=geom
                    )
                )
                processed_count += 1

                # Bulk create in batches
                if len(tigerline_objects) >= batch_size:
                    USCountyTigerline.objects.bulk_create(
                        tigerline_objects,
                        batch_size=batch_size
                    )
                    print(
                        f"Processed {processed_count} rows, "
                        f"inserted batch of {len(tigerline_objects)}"
                    )
                    tigerline_objects = []

            except Exception as e:
                error_count += 1
                print(
                    f"Error processing row {row_idx} (geoid={geoid}): {str(e)}"
                )
                continue

        # Create remaining objects
        if tigerline_objects:
            USCountyTigerline.objects.bulk_create(
                tigerline_objects,
                batch_size=batch_size
            )
            print(
                f"Processed {processed_count} rows, "
                f"inserted final batch of {len(tigerline_objects)}"
            )

    total_count = USCountyTigerline.objects.count()
    print(
        f"Successfully loaded {total_count} counties. "
        f"Processed: {processed_count}, Errors: {error_count}"
    )


def clean_tigerline_data(apps, schema_editor):
    '''
    Clean the USCountyTigerline table.
    '''
    USCountyTigerline = apps.get_model('api', 'USCountyTigerline')
    USCountyTigerline.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_populate_wage_indicator_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='USCountyTigerline',
            fields=[
                ('geoid', models.CharField(
                    help_text='The Geo ID of the county (US)',
                    max_length=50,
                    primary_key=True
                )),
                ('name', models.CharField(
                    help_text='The name of the county',
                    max_length=255
                )),
                ('geometry', gis_models.MultiPolygonField(
                    help_text='The MultiPolygon geometry of the county in EPSG:5070',
                    srid=5070
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'US County Tigerline',
                'verbose_name_plural': 'US County Tigerline',
            },
        ),
        migrations.RunPython(
            populate_tigerline_data,
            reverse_code=clean_tigerline_data
        ),
    ]

