# Generated by Django 3.2.17 on 2025-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_populate_wage_indicator_country_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MITLivingWageCountyData',
            fields=[
                ('us_geoid_county', models.CharField(
                    help_text=(
                        'The Geo Id of county (US)'
                    ),
                    max_length=50
                )),
                ('country_code', models.CharField(
                    help_text=(
                        'ISO 3166-1 alpha-2 country code '
                        '(e.g., US, MX, PR).'
                    ),
                    max_length=2,
                    serialize=False
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MIT Living Wage County Data',
                'verbose_name_plural': 'MIT Living Wage County Data',
            },
        ),
    ]
