# Generated by Django 3.2.17 on 2025-12-16

from django.db import migrations, models
from django.contrib.gis.db import models as gis_models
from api.migrations._tigerline_helper import (
    populate_tigerline_data,
    clear_tigerline_data
)

S3_CSV_KEY = 'data/us_county_tigerline_2021.csv'


def populate_tigerline_data_wrapper(apps, schema_editor):
    '''
    Populate the USCountyTigerline table with 2021 data from CSV file.
    Geometry data is in EPSG:4326 (WGS84).
    '''
    populate_tigerline_data(
        apps,
        s3_key=S3_CSV_KEY,
        source_srid=4326,
        clear_existing=False,
        production_envs=['Production', 'Staging']
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_populate_wage_indicator_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='USCountyTigerline',
            fields=[
                ('geoid', models.CharField(
                    help_text='The Geo ID of the county (US)',
                    max_length=50,
                    primary_key=True
                )),
                ('name', models.CharField(
                    help_text='The name of the county',
                    max_length=255
                )),
                ('geometry', gis_models.MultiPolygonField(
                    help_text='The MultiPolygon geometry of the county in EPSG:5070',
                    srid=5070
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'County (US)',
                'verbose_name_plural': 'Counties (US)',
            },
        ),
        migrations.RunPython(
            populate_tigerline_data_wrapper,
            reverse_code=clear_tigerline_data
        ),
    ]
