# Generated by Django 3.2.17 on 2025-12-16

import csv
import io
import os
import sys

import boto3
from django.conf import settings
from django.db import migrations, models
from django.contrib.gis.db import models as gis_models
from django.contrib.gis.geos import GEOSGeometry, MultiPolygon

# Increase CSV field size limit to handle large geometry WKT strings
csv.field_size_limit(sys.maxsize)

# S3 key for the CSV file
S3_CSV_KEY = 'data/us_county_tigerline_2025.csv'


def get_s3_client():
    '''
    Create S3 client with MinIO support for local development.
    '''
    endpoint_url = os.getenv('AWS_S3_ENDPOINT_URL')

    if endpoint_url:
        # Local development with MinIO
        return boto3.client(
            's3',
            endpoint_url=endpoint_url,
            aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
            aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
            region_name=os.getenv('AWS_REGION', 'us-east-1'),
        )
    else:
        # Production AWS S3
        return boto3.client('s3')


def download_csv_from_s3():
    '''
    Download the CSV file from S3 bucket.
    Returns the CSV content as a string.
    '''
    bucket_name = settings.AWS_STORAGE_BUCKET_NAME
    if not bucket_name:
        raise ValueError(
            'AWS_STORAGE_BUCKET_NAME is not configured. '
            'Cannot download CSV from S3.'
        )

    s3_client = get_s3_client()
    response = s3_client.get_object(Bucket=bucket_name, Key=S3_CSV_KEY)
    return response['Body'].read().decode('utf-8')


def get_csv_reader():
    '''
    Get CSV reader from S3 (or MinIO for local development).
    Returns CSV DictReader.
    '''
    csv_content = download_csv_from_s3()
    return csv.DictReader(io.StringIO(csv_content))


def populate_tigerline_data(apps, schema_editor):
    '''
    Populate the USCountyTigerline table with data from CSV file.
    Downloads from S3 or MinIO.
    In live environments, raises error if CSV file not found.
    Geometry data is already in EPSG:5070 (Albers Equal Area).
    '''
    us_county_tigerline = apps.get_model('api', 'USCountyTigerline')

    try:
        reader = get_csv_reader()
    except Exception as e:
        env = os.getenv('DJANGO_ENV', 'Local')

        if env == 'Local':
            return

        raise Exception(
            f'Failed to download CSV file from S3: {e}. '
            f'CSV file is required in {env} environment.'
        ) from e

    tigerline_objects = []
    batch_size = 2000

    for _, row in enumerate(reader, start=1):
        geoid = row['geoid'].strip()
        name = row['name'].strip()
        geometry_wkt = row['geometry'].strip()

        if not geoid or not name or not geometry_wkt:
            continue

        geom = GEOSGeometry(geometry_wkt, srid=5070)

        if geom.geom_type not in ("Polygon", "MultiPolygon"):
            raise ValueError(
                f'Unexpected geometry type: {geom.geom_type}'
            )

        if geom.geom_type == "Polygon":
            geom = MultiPolygon(geom, srid=5070)

        tigerline_objects.append(
            us_county_tigerline(
                geoid=geoid,
                name=name,
                geometry=geom
            )
        )

        if len(tigerline_objects) >= batch_size:
            us_county_tigerline.objects.bulk_create(
                tigerline_objects,
                batch_size=batch_size
            )
            tigerline_objects = []

    if tigerline_objects:
        us_county_tigerline.objects.bulk_create(
            tigerline_objects,
            batch_size=batch_size
        )


def clean_tigerline_data(apps, schema_editor):
    '''
    Clean the USCountyTigerline table.
    '''
    us_county_tigerline = apps.get_model('api', 'USCountyTigerline')
    us_county_tigerline.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_populate_wage_indicator_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='USCountyTigerline',
            fields=[
                ('geoid', models.CharField(
                    help_text='The Geo ID of the county (US)',
                    max_length=50,
                    primary_key=True
                )),
                ('name', models.CharField(
                    help_text='The name of the county',
                    max_length=255
                )),
                ('geometry', gis_models.MultiPolygonField(
                    help_text='The MultiPolygon geometry of the county in EPSG:5070',
                    srid=5070
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'US County Tigerline',
                'verbose_name_plural': 'US County Tigerline',
            },
        ),
        migrations.RunPython(
            populate_tigerline_data,
            reverse_code=clean_tigerline_data
        ),
    ]

