# Generated by Django 3.2.17 on 2025-12-16

from django.db import migrations


def create_mit_living_wage_partner_field(apps, schema_editor):
    '''
    Create the mit_living_wage partner field.
    '''
    PartnerField = apps.get_model('api', 'PartnerField')
    
    # Check if partner field already exists
    if PartnerField.objects.filter(name='mit_living_wage').exists():
        print('Partner field mit_living_wage already exists. Skipping creation.')
        return
    
    json_schema = {
        "type": "object",
        "title": "Some Data",
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "properties": {
            "value": {
                "type": "string",
                "title": "County Id",
                "format": "uri-reference"
            }
        }
    }
    
    PartnerField.objects.create(
        name='mit_living_wage',
        type='object',
        json_schema=json_schema,
        base_url='https://livingwage.mit.edu/counties/',
        display_text='View Living Wage Data for this County',
        active=True,
        system_field=True

    )
    print('Successfully created mit_living_wage partner field.')


def remove_mit_living_wage_partner_field(apps, schema_editor):
    '''
    Remove the mit_living_wage partner field.
    '''
    PartnerField = apps.get_model('api', 'PartnerField')
    PartnerField.objects.filter(name='mit_living_wage').delete()
    print('Removed mit_living_wage partner field.')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_create_and_populate_us_county_tigerline'),
    ]

    operations = [
        migrations.RunPython(
            create_mit_living_wage_partner_field,
            reverse_code=remove_mit_living_wage_partner_field
        ),
    ]

