# Generated by Django 3.2.17 on 2026-01-06

from django.db import migrations
from api.migrations._tigerline_helper import (
    populate_tigerline_data
)

S3_CSV_KEY_2021 = 'data/us_county_tigerline_2021.csv'
S3_CSV_KEY_2025 = 'data/us_county_tigerline_2025.csv'


def populate_tigerline_2021_data(apps, schema_editor):
    '''
    Clear existing data and populate the USCountyTigerline table with 2021 data from CSV file.
    Geometry data is in EPSG:4326 (WGS84) and will be transformed to EPSG:5070.
    '''
    populate_tigerline_data(
        apps,
        s3_key=S3_CSV_KEY_2021,
        source_srid=4326,
        clear_existing=True,
        production_envs=['Production', 'Preprod', 'Staging']
    )


def reverse_populate_tigerline_2021_data(apps, schema_editor):
    '''
    Reverse operation: re-populate with 2025 data from CSV file.
    This restores the original 2025 data when the migration is reversed.
    '''
    populate_tigerline_data(
        apps,
        s3_key=S3_CSV_KEY_2025,
        source_srid=5070,
        clear_existing=True,
        production_envs=['Production', 'Preprod', 'Staging']
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_add_mit_livingwage_partner_field'),
    ]

    operations = [
        migrations.RunPython(
            populate_tigerline_2021_data,
            reverse_code=reverse_populate_tigerline_2021_data
        ),
    ]

