# Generated by Django 5.2.10 on 2026-02-10 07:43

import django.contrib.postgres.fields
from django.db import migrations, models

# 0177 list + ('Rainforest Alliance', 'Rainforest Alliance').
CERTIFICATION_CHOICES = [
        ('BCI', 'BCI'),
        ('B Corp', 'B Corp'),
        ('Bluesign', 'Bluesign'),
        ('Canopy', 'Canopy'),
        ('Cradle to Cradle', 'Cradle to Cradle'),
        ('EU Ecolabel', 'EU Ecolabel'),
        ('Fairtrade USA', 'Fairtrade USA'),
        ('FSC', 'FSC'),
        ('Global Recycling Standard (GRS)', 'Global Recycling Standard (GRS)'),
        ('GOTS', 'GOTS'),
        ('Green Button', 'Green Button'),
        ('Green Screen for Safer Chemicals', 'Green Screen for Safer Chemicals'),
        ('Higg Index', 'Higg Index'),
        ('IMO Control', 'IMO Control'),
        ('International Wool Textile Organisation (IWTO)', 'International Wool Textile Organisation (IWTO)'),
        ('ISO 9000', 'ISO 9000'),
        ('IVN leather', 'IVN leather'),
        ('Leather Working Group', 'Leather Working Group'),
        ('Nordic Swan', 'Nordic Swan'),
        ('Oeko-Tex Standard 100', 'Oeko-Tex Standard 100'),
        ('Oeko-Tex STeP', 'Oeko-Tex STeP'),
        ('Oeko-Tex Eco Passport', 'Oeko-Tex Eco Passport'),
        ('Oeko-Tex Made in Green', 'Oeko-Tex Made in Green'),
        ('PEFC', 'PEFC'),
        ('REACH', 'REACH'),
        ('Responsible Down Standard (RDS)', 'Responsible Down Standard (RDS)'),
        ('Responsible Wool Standard (RWS)', 'Responsible Wool Standard (RWS)'),
        ('Rainforest Alliance', 'Rainforest Alliance'),  # New option
        ('SA8000', 'SA8000'),
        ('ABVTEX', 'ABVTEX'),
        ('Empresa B', 'Empresa B'),
        ('Origem Sustentável', 'Origem Sustentável'),
        ('Selo ABR', 'Selo ABR'),
]


class Migration(migrations.Migration):
    """
    Add Rainforest Alliance to facility_certifications choices.
    Django requires the full choices list in AlterField (no "append" operation);
    the DB column is unchanged (varchar array), only the app state is updated.
    """

    dependencies = [
        ('api', '0197_add_event_index'),
    ]

    def _facility_certifications_field():
        return django.contrib.postgres.fields.ArrayField(
            base_field=models.CharField(
                choices=CERTIFICATION_CHOICES,
                help_text='A certification the facility has achieved',
                max_length=50,
                verbose_name='facility certification',
            ),
            blank=True,
            help_text="The facility's certifications",
            null=True,
            size=None,
            verbose_name='facility certifications',
        )

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='facilityclaim',
                    name='facility_certifications',
                    field=_facility_certifications_field(),
                ),
                migrations.AlterField(
                    model_name='historicalfacilityclaim',
                    name='facility_certifications',
                    field=_facility_certifications_field(),
                ),
            ],
        ),
    ]
