# Generated by Django 5.2.10 on 2026-02-18 10:54

from django.db.migrations import Migration, RunPython
from django.db import connection


from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def update_indexing_function(apps, schema_editor):
    '''
    This function replaces the old index_claim_info function with a similar
    one that additionally indexes the creation date of the claim request.
    '''

    helper.run_sql_files([
        '0200_index_claim_info.sql'
    ])


def revert_updating_indexing_function(apps, schema_editor):
    helper.run_sql_files([
        '0188_index_claim_info.sql'
    ])


class Migration(Migration):

    dependencies = [
        ('api', '0199_add_production_location_page_switch'),
    ]

    operations = [
        RunPython(update_indexing_function,
                  revert_updating_indexing_function)
    ]
