# Generated by Django 5.2.10 on 2026-02-26 13:28

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0200_introduce_indexing_of_the_creation_date_of_the_claim_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerFieldGroup",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the partner field group.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The partner field group name.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order for the partner field group in the UI.",
                    ),
                ),
                (
                    "icon_file",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an icon image.",
                        null=True,
                        upload_to="partner_field_groups/icons/",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Rich text description of the partner field group.",
                        null=True,
                    ),
                ),
                (
                    "helper_text",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Rich text helper text for the partner field group.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={
                "verbose_name_plural": "Partner field groups",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="partnerfield",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="The group this partner field belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_fields",
                to="api.partnerfieldgroup",
            ),
        ),
    ]
