# Generated by Django 5.2.10 on 2026-03-10 16:21

import api.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0201_add_partnerfieldgroup_alter_partnerfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerfield",
            name="json_schema",
            field=api.fields.JSONTextField(
                blank=True,
                help_text='JSON Schema for validating object type partner fields. Used when type is "object".',
                null=True,
            ),
        ),
    ]
