# Generated by Django 5.2.10 on 2026-03-16

from django.db.migrations import Migration, RunPython
from django.db import connection

from api.migrations._migration_helper import MigrationHelper

helper = MigrationHelper(connection)


def update_indexing_function(apps, schema_editor):
    """
    Replace index_claim_info with a version that includes user_id
    (contributor admin id) in the contributor object for profile links.
    """
    helper.run_sql_files([
        '0203_index_claim_info.sql'
    ])


def revert_indexing_function(apps, schema_editor):
    helper.run_sql_files([
        '0200_index_claim_info.sql'
    ])


class Migration(Migration):

    dependencies = [
        ('api', '0202_add_alter_partnerfield_to_use_json'),
    ]

    operations = [
        RunPython(update_indexing_function, revert_indexing_function)
    ]
