# Generated by Django 5.2.10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_add_user_id_to_index_claim_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationevent',
            name='backfilled_fields',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text=(
                    'List of field names (e.g. name, address, country) that were '
                    'backfilled from existing production location data when the API '
                    'user did not provide them in a PATCH request.'
                ),
                size=None,
            ),
        ),
    ]
