# Generated by Django 5.2.10 on 2026-03-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_add_backfilled_fields_to_moderation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylistitem',
            name='moderation_event',
            field=models.OneToOneField(
                blank=True,
                help_text=(
                    'The moderation event whose approval flow created this '
                    'list item, when applicable (e.g. production location '
                    'moderation pipeline). At most one list item per '
                    'moderation event.'
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='api.moderationevent',
            ),
        )
    ]
