# Generated by Django 5.2.10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0210_deactivate_rejected_list_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerDataFileUpload",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "google_drive_file_link",
                    models.URLField(
                        help_text=(
                            "Link to a Google Sheet stored in Google Drive. "
                            "The sheet must include an os_id column and "
                            "partner field columns the contributor is "
                            "authorized to write."
                        ),
                        max_length=2000,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text=(
                            "Updated automatically when the partner list file "
                            "is processed. PENDING: saved and waiting to be "
                            "queued. PROCESSING: the file is being read and "
                            "partner data is being applied. PROCESSED: "
                            "finished successfully (check the Google Sheet "
                            "error column for any individual rows that need "
                            "fixes). FAILED: the file could not be "
                            "processed—read Processing error for what went "
                            "wrong, correct the sheet or settings, and "
                            "submit a new upload."
                        ),
                        max_length=20,
                    ),
                ),
                (
                    "batch_job_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AWS Batch job ID used for processing this file.",
                        max_length=128,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this file finished processing.",
                        null=True,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text=(
                            "When status is Failed, explains what went wrong. "
                            "Messages starting with 'Contact developers:' are "
                            "for the engineering team. Other messages usually "
                            "mean fixes are needed in the Google Sheet before "
                            "you submit again."
                        ),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        help_text="Contributor attributed to created moderation events.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_data_file_uploads",
                        to="api.contributor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator who created this ingestion request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_partner_data_file_uploads",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
