# Generated by Django 5.2.10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0210_deactivate_rejected_list_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerDataFileUpload",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "google_drive_file_link",
                    models.URLField(
                        help_text="Link to a Google Sheet stored in Google Drive.",
                        max_length=2000,
                    ),
                ),
                (
                    "columns_to_process",
                    models.TextField(
                        help_text=(
                            "Comma-separated list of sheet columns that "
                            "should be processed, for example: "
                            "os_id,name,address,country,sector."
                        ),
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this file has already been processed.",
                    ),
                ),
                (
                    "batch_job_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AWS Batch job ID used for processing this file.",
                        max_length=128,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this file finished processing.",
                        null=True,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Terminal processing error when ingestion fails.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        help_text="Contributor attributed to created moderation events.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_data_file_uploads",
                        to="api.contributor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator who created this ingestion request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_partner_data_file_uploads",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
