from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add composite (id, history_date) indexes to the historical_* tables read
    by the Change Intelligence Phase 1 signal queries (OSDEV-2839), which run
    `LAG(...) OVER (PARTITION BY id ORDER BY history_date)`.

    Without these, each watchlist query sorts every candidate row at
    production scale (~11.1M rows on api_historicalextendedfield). Built
    CONCURRENTLY so index creation takes no table lock; this requires a
    non-atomic migration.

    The operations are database-only (SeparateDatabaseAndState with no state
    operations): the historical_* models are auto-generated by
    django-simple-history and do not declare these indexes in their Meta, so
    recording them in Django's migration state would make the autodetector
    emit RemoveIndex operations on the next makemigrations run.

    If a concurrent build is interrupted, Postgres leaves an INVALID index:
    detect with `SELECT relname FROM pg_class c JOIN pg_index i ON
    i.indexrelid = c.oid WHERE NOT i.indisvalid;` then DROP INDEX and re-run
    the migration. See OSDEV-2897 for the full test/deploy plan.
    """

    atomic = False

    dependencies = [
        ('api', '0217_add_contribution_dates_to_index_contributors'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                AddIndexConcurrently(
                    model_name='historicalfacility',
                    index=models.Index(
                        fields=['id', 'history_date'],
                        name='hist_facility_id_histdate_idx',
                    ),
                ),
                AddIndexConcurrently(
                    model_name='historicalextendedfield',
                    index=models.Index(
                        fields=['id', 'history_date'],
                        name='hist_extfield_id_histdate_idx',
                    ),
                ),
                AddIndexConcurrently(
                    model_name='historicalfacilityclaim',
                    index=models.Index(
                        fields=['id', 'history_date'],
                        name='hist_claim_id_histdate_idx',
                    ),
                ),
            ],
            state_operations=[],
        ),
    ]
