# Generated by Django 5.2.16 on 2026-07-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_add_contributor_anonymise_in_paid_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitylistitem',
            name='ai_usage_notes',
            field=models.TextField(blank=True, help_text='Details of any AI usage during collection: model and version, tasks performed, and extent of human review.', null=True),
        ),
        migrations.AddField(
            model_name='facilitylistitem',
            name='data_collection_methodology',
            field=models.TextField(blank=True, help_text='How the data was collected (e.g. copied from a website, scraped, downloaded directly from source).', null=True),
        ),
        migrations.AddField(
            model_name='facilitylistitem',
            name='date_of_source',
            field=models.CharField(blank=True, help_text='Timestamp stated by the external source, kept as raw text (specific date, month, and/or year).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facilitylistitem',
            name='information_source_type',
            field=models.CharField(blank=True, help_text='Type of the external information source (e.g. air quality permit, press release, company website). Renamed from the schema field "source_type" to avoid colliding with Source.source_type.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facilitylistitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes on judgment calls made during data collection.', null=True),
        ),
        migrations.AddField(
            model_name='facilitylistitem',
            name='source_link',
            field=models.URLField(blank=True, help_text='Link to the external source for this row.', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='facilitylistitem',
            name='source_name',
            field=models.CharField(blank=True, help_text='Name of the external information source this row came from (e.g. "US EPA FRS", an operator website).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='extendedfield',
            name='field_name',
            field=models.CharField(choices=[('name', 'name'), ('address', 'address'), ('number_of_workers', 'number_of_workers'), ('native_language_name', 'native_language_name'), ('facility_type', 'facility_type'), ('processing_type', 'processing_type'), ('product_type', 'product_type'), ('parent_company', 'parent_company'), ('parent_company_os_id', 'parent_company_os_id'), ('duns_id', 'duns_id'), ('lei_id', 'lei_id'), ('rba_id', 'rba_id'), ('isic_4', 'isic_4'), ('name_unspecified', 'name_unspecified'), ('name_site_other', 'name_site_other'), ('name_owner', 'name_owner'), ('name_property_manager', 'name_property_manager'), ('name_operator', 'name_operator'), ('name_permit_holder', 'name_permit_holder'), ('name_building_owner', 'name_building_owner'), ('name_tenant', 'name_tenant'), ('capacity', 'capacity'), ('capacity_units', 'capacity_units'), ('it_capacity', 'it_capacity'), ('it_capacity_units', 'it_capacity_units'), ('utility_capacity', 'utility_capacity'), ('utility_capacity_units', 'utility_capacity_units'), ('ups_capacity', 'ups_capacity'), ('ups_capacity_units', 'ups_capacity_units'), ('backup_generator_capacity', 'backup_generator_capacity'), ('backup_generator_capacity_units', 'backup_generator_capacity_units'), ('pue', 'pue'), ('power_providers', 'power_providers'), ('power_sources', 'power_sources'), ('power_density', 'power_density'), ('power_density_units', 'power_density_units'), ('water_usage', 'water_usage'), ('water_usage_units', 'water_usage_units'), ('wue', 'wue'), ('cooling_mechanism', 'cooling_mechanism'), ('operational_status', 'operational_status'), ('is_data_center', 'is_data_center'), ('certifications_compliance', 'certifications_compliance'), ('time_zones', 'time_zones'), ('date_operational', 'date_operational'), ('area', 'area'), ('area_units', 'area_units'), ('data_area', 'data_area'), ('data_area_units', 'data_area_units'), ('floor_space', 'floor_space'), ('floor_space_units', 'floor_space_units'), ('overall_area', 'overall_area'), ('overall_area_units', 'overall_area_units'), ('other_area', 'other_area'), ('other_area_notes', 'other_area_notes'), ('other_area_units', 'other_area_units'), ('number_of_servers', 'number_of_servers'), ('number_of_racks', 'number_of_racks')], help_text='The name of the field, chosen from a strict list.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalextendedfield',
            name='field_name',
            field=models.CharField(choices=[('name', 'name'), ('address', 'address'), ('number_of_workers', 'number_of_workers'), ('native_language_name', 'native_language_name'), ('facility_type', 'facility_type'), ('processing_type', 'processing_type'), ('product_type', 'product_type'), ('parent_company', 'parent_company'), ('parent_company_os_id', 'parent_company_os_id'), ('duns_id', 'duns_id'), ('lei_id', 'lei_id'), ('rba_id', 'rba_id'), ('isic_4', 'isic_4'), ('name_unspecified', 'name_unspecified'), ('name_site_other', 'name_site_other'), ('name_owner', 'name_owner'), ('name_property_manager', 'name_property_manager'), ('name_operator', 'name_operator'), ('name_permit_holder', 'name_permit_holder'), ('name_building_owner', 'name_building_owner'), ('name_tenant', 'name_tenant'), ('capacity', 'capacity'), ('capacity_units', 'capacity_units'), ('it_capacity', 'it_capacity'), ('it_capacity_units', 'it_capacity_units'), ('utility_capacity', 'utility_capacity'), ('utility_capacity_units', 'utility_capacity_units'), ('ups_capacity', 'ups_capacity'), ('ups_capacity_units', 'ups_capacity_units'), ('backup_generator_capacity', 'backup_generator_capacity'), ('backup_generator_capacity_units', 'backup_generator_capacity_units'), ('pue', 'pue'), ('power_providers', 'power_providers'), ('power_sources', 'power_sources'), ('power_density', 'power_density'), ('power_density_units', 'power_density_units'), ('water_usage', 'water_usage'), ('water_usage_units', 'water_usage_units'), ('wue', 'wue'), ('cooling_mechanism', 'cooling_mechanism'), ('operational_status', 'operational_status'), ('is_data_center', 'is_data_center'), ('certifications_compliance', 'certifications_compliance'), ('time_zones', 'time_zones'), ('date_operational', 'date_operational'), ('area', 'area'), ('area_units', 'area_units'), ('data_area', 'data_area'), ('data_area_units', 'data_area_units'), ('floor_space', 'floor_space'), ('floor_space_units', 'floor_space_units'), ('overall_area', 'overall_area'), ('overall_area_units', 'overall_area_units'), ('other_area', 'other_area'), ('other_area_notes', 'other_area_notes'), ('other_area_units', 'other_area_units'), ('number_of_servers', 'number_of_servers'), ('number_of_racks', 'number_of_racks')], help_text='The name of the field, chosen from a strict list.', max_length=200),
        ),
    ]
