# Generated by Django 5.2.10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from api.migrations._isic_taxonomy_helper import (
    clear_isic_taxonomy_config,
    seed_isic_taxonomy_config,
)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0226_add_isic_to_facility_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsicTaxonomyConfig',
            fields=[
                (
                    'id',
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=False,
                        help_text=(
                            'When enabled, the ISIC Rev 4 filter and combine '
                            'checkbox are shown in extended search.'
                        ),
                    ),
                ),
                (
                    'version',
                    models.PositiveIntegerField(
                        default=0,
                        help_text=(
                            'Monotonic publish version; used in the S3 key '
                            'prefix.'
                        ),
                    ),
                ),
                (
                    'source_file',
                    models.FileField(
                        blank=True,
                        help_text='Most recently uploaded taxonomy spreadsheet.',
                        null=True,
                        upload_to='taxonomy/isic4/source/',
                    ),
                ),
                (
                    'source_filename',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text=(
                            'Original filename from the admin upload, for '
                            'display only.'
                        ),
                        max_length=255,
                    ),
                ),
                (
                    'json_s3_key',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='S3 key for the published isic_rev4.json artifact.',
                        max_length=512,
                    ),
                ),
                (
                    'bundle_s3_key',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text=(
                            'S3 key for the published isicRev4Taxonomy.js '
                            'bundle.'
                        ),
                        max_length=512,
                    ),
                ),
                ('section_count', models.PositiveIntegerField(default=0)),
                ('division_count', models.PositiveIntegerField(default=0)),
                ('group_count', models.PositiveIntegerField(default=0)),
                ('class_count', models.PositiveIntegerField(default=0)),
                (
                    'published_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when the active version was published.',
                        null=True,
                    ),
                ),
                (
                    'last_error',
                    models.TextField(
                        blank=True,
                        default='',
                        help_text=(
                            'Human-readable failure from the most recent '
                            'publish attempt.'
                        ),
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            'Staff user who published the active taxonomy '
                            'version.'
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='isic_taxonomy_uploads',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'ISIC taxonomy configuration',
                'verbose_name_plural': 'ISIC taxonomy configuration',
            },
        ),
        migrations.RunPython(
            seed_isic_taxonomy_config,
            reverse_code=clear_isic_taxonomy_config,
        ),
    ]
