export const REACT_APP_GOOGLE_ANALYTICS_KEY = 'REACT_APP_GOOGLE_ANALYTICS_KEY';

export const GA_TRACKING = 'GA_TRACKING';
export const GA_TRACKING_DECISION_DATE = 'GA_TRACKING_DECISION_DATE';
export const HAS_ACCEPTED_GA_TRACKING = 'HAS_ACCEPTED_GA_TRACKING';
export const HAS_REJECTED_GA_TRACKING = 'HAS_REJECTED_GA_TRACKING';

export const GA_EVENTS = Object.freeze({
    TRACKING_CONSENT: 'TRACKING_CONSENT',
    LOCATION_PARTNER_PROFILE_LINK_CLICK: 'LOCATION_PARTNER_PROFILE_LINK_CLICK',
    LOCATION_PARTNER_EXTERNAL_LINK_CLICK:
        'LOCATION_PARTNER_EXTERNAL_LINK_CLICK',
    CONTRIBUTOR_EXTERNAL_WEBSITE_LINK_CLICK:
        'CONTRIBUTOR_EXTERNAL_WEBSITE_LINK_CLICK',
});

export const GA_LINK_PLACEMENT = Object.freeze({
    CONTRIBUTION_LINE: 'contribution_line',
    CONTRIBUTIONS_DRAWER: 'contributions_drawer',
});
