known_countries = [
    "abw",
    "ad",
    "ae",
    "af",
    "afg",
    "afghanistan",
    "ag",
    "ago",
    "ai",
    "aia",
    "al",
    "ala",
    "alb",
    "albania",
    "algeria",
    "am",
    "american samoa",
    "and",
    "andorra",
    "angola",
    "anguilla",
    "antarctica",
    "antigua",
    "antigua & barbuda",
    "antigua and barbuda",
    "ao",
    "aq",
    "ar",
    "arab republic of egypt",
    "are",
    "arg",
    "argentina",
    "argentine republic",
    "arm",
    "armenia",
    "aruba",
    "as",
    "asm",
    "at",
    "ata",
    "atf",
    "atg",
    "au",
    "aus",
    "australia",
    "austria",
    "aut",
    "aw",
    "ax",
    "az",
    "aze",
    "azerbaijan",
    "ba",
    "bahamas",
    "bahamas (the)",
    "bahamas, the",
    "bahrain",
    "bangladesh",
    "barbados",
    "barbuda",
    "bb",
    "bd",
    "bdi",
    "be",
    "bel",
    "belarus",
    "belgium",
    "belize",
    "ben",
    "benin",
    "bermuda",
    "bes",
    "bf",
    "bfa",
    "bg",
    "bgd",
    "bgr",
    "bh",
    "bhr",
    "bhs",
    "bhutan",
    "bi",
    "bih",
    "bj",
    "bl",
    "blm",
    "blr",
    "blz",
    "bm",
    "bmu",
    "bn",
    "bo",
    "bol",
    "bolivarian republic of venezuela",
    "bolivia",
    "bolivia (plurinational state of)",
    "bolivia, plurinational state of",
    "bonaire (sint eustatius & saba)",
    "bonaire (sint eustatius and saba)",
    "bonaire, sint eustatius & saba",
    "bonaire, sint eustatius and saba",
    "bosnia",
    "bosnia & herzegovina",
    "bosnia and herzegovina",
    "botswana",
    "bouvet island",
    "bq",
    "br",
    "bra",
    "brazil",
    "brb",
    "britain",
    "british indian ocean territory",
    "british virgin islands",
    "brn",
    "brunei",
    "brunei darussalam",
    "bs",
    "bt",
    "btn",
    "bulgaria",
    "burkina faso",
    "burma",
    "burundi",
    "bv",
    "bvt",
    "bw",
    "bwa",
    "by",
    "bz",
    "ca",
    "cabo verde",
    "caf",
    "cambodia",
    "cameroon",
    "can",
    "canada",
    "cape verde",
    "cayman islands",
    "cayman islands (the)",
    "cayman islands, the",
    "cc",
    "cck",
    "cd",
    "central african republic",
    "central african republic (the)",
    "central african republic, the",
    "cf",
    "cg",
    "ch",
    "chad",
    "channel islands",
    "che",
    "chile",
    "china",
    "china (hong kong sar)",
    "china (macao sar)",
    "china (taiwan province of china)",
    "china, hong kong sar",
    "china, macao sar",
    "china, taiwan province of china",
    "chl",
    "chn",
    "christmas island",
    "ci",
    "civ",
    "ck",
    "cl",
    "cm",
    "cmr",
    "cn",
    "co",
    "cocos (keeling) islands",
    "cod",
    "cog",
    "cok",
    "col",
    "colombia",
    "com",
    "commonwealth of dominica",
    "commonwealth of the bahamas",
    "commonwealth of the northern mariana islands",
    "comoros",
    "comoros (the)",
    "comoros, the",
    "congo",
    "congo (brazzaville)",
    "congo (democratic republic of the)",
    "congo (kinshasa)",
    "congo (the democratic republic of the)",
    "congo (the)",
    "congo, brazzaville",
    "congo, democratic republic of the",
    "congo, kinshasa",
    "congo, the",
    "congo, the democratic republic of the",
    "cook islands",
    "cook islands (the)",
    "cook islands, the",
    "costa rica",
    "cote d'ivoire",
    "cote d´ivoire",
    "cpv",
    "cr",
    "cri",
    "croatia",
    "cu",
    "cub",
    "cuba",
    "curacao",
    "curaçao",
    "cuw",
    "cv",
    "cw",
    "cx",
    "cxr",
    "cy",
    "cym",
    "cyp",
    "cyprus",
    "cz",
    "cze",
    "czech",
    "czech republic",
    "czechia",
    "czechia (czech republic)",
    "czechia, czech republic",
    "côte d'ivoire",
    "côte d´ivoire",
    "de",
    "dem. people's republic of korea",
    "dem. people´s republic of korea",
    "democratic people's republic of korea",
    "democratic people´s republic of korea",
    "democratic republic of sao tome & principe",
    "democratic republic of sao tome and principe",
    "democratic republic of the congo",
    "democratic republic of timor-leste",
    "democratic socialist republic of sri lanka",
    "denmark",
    "deu",
    "dj",
    "dji",
    "djibouti",
    "dk",
    "dm",
    "dma",
    "dnk",
    "do",
    "dom",
    "dominica",
    "dominican republic",
    "dominican republic (the)",
    "dominican republic, the",
    "dz",
    "dza",
    "dänemark",
    "eastern republic of uruguay",
    "ec",
    "ecu",
    "ecuador",
    "ee",
    "eg",
    "egy",
    "egypt",
    "eh",
    "el salvador",
    "equatorial guinea",
    "er",
    "eri",
    "eritrea",
    "es",
    "esh",
    "esp",
    "est",
    "estonia",
    "eswatini",
    "et",
    "eth",
    "ethiopia",
    "falkl& isl&s (malvinas)",
    "falkl& isl&s (the) [malvinas]",
    "falkl& isl&s, malvinas",
    "falkland islands (malvinas)",
    "falkland islands (the) [malvinas]",
    "falkland islands, malvinas",
    "faroe islands",
    "faroe islands (the)",
    "faroe islands, the",
    "federal democratic republic of ethiopia",
    "federal democratic republic of nepal",
    "federal republic of germany",
    "federal republic of nigeria",
    "federal republic of somalia",
    "federated states of micronesia",
    "federative republic of brazil",
    "fi",
    "fiji",
    "fin",
    "finland",
    "fj",
    "fji",
    "fk",
    "flk",
    "fm",
    "fo",
    "fr",
    "fra",
    "france",
    "french guiana",
    "french polynesia",
    "french republic",
    "french southern territories",
    "fro",
    "fsm",
    "ga",
    "gab",
    "gabon",
    "gabonese republic",
    "gambia",
    "gambia (the)",
    "gambia, the",
    "gb",
    "gbr",
    "gd",
    "ge",
    "geo",
    "georgia",
    "germany",
    "gf",
    "gg",
    "ggy",
    "gh",
    "gha",
    "ghana",
    "gi",
    "gib",
    "gibraltar",
    "gin",
    "gl",
    "glp",
    "gm",
    "gmb",
    "gn",
    "gnb",
    "gnq",
    "gp",
    "gq",
    "gr",
    "gr& duchy of luxembourg",
    "grand duchy of luxembourg",
    "grc",
    "grd",
    "great britain",
    "greece",
    "greenland",
    "grenada",
    "grl",
    "gs",
    "gt",
    "gtm",
    "gu",
    "guadeloupe",
    "guam",
    "guatemala",
    "guernsey",
    "guf",
    "guinea",
    "guinea-bissau",
    "gum",
    "guy",
    "guyana",
    "gw",
    "gy",
    "haiti",
    "hashemite kingdom of jordan",
    "heard isl& & mcdonald isl&s",
    "heard island and mcdonald islands",
    "hellenic republic",
    "herzegovina",
    "hk",
    "hkg",
    "hm",
    "hmd",
    "hn",
    "hnd",
    "holland",
    "holy see",
    "holy see (the)",
    "holy see (vatican city state)",
    "holy see, the",
    "holy see, vatican city state",
    "honduras",
    "hong kong",
    "hong kong (china (sar))",
    "hong kong (china)",
    "hong kong (china, sar)",
    "hong kong special administrative region of china",
    "hong kong, china",
    "hong kong, china (sar)",
    "hong kong, china, sar",
    "hr",
    "hrv",
    "ht",
    "hti",
    "hu",
    "hun",
    "hungary",
    "iceland",
    "id",
    "idn",
    "ie",
    "il",
    "im",
    "imn",
    "in",
    "ind",
    "independent state of papua new guinea",
    "independent state of samoa",
    "india",
    "indonega",
    "indonesia",
    "io",
    "iot",
    "iq",
    "ir",
    "iran",
    "iran (islamic republic of)",
    "iran, islamic republic of",
    "iraq",
    "ireland",
    "irl",
    "irn",
    "irq",
    "is",
    "isl",
    "islamic republic of afghanistan",
    "islamic republic of iran",
    "islamic republic of mauritania",
    "islamic republic of pakistan",
    "isle of man",
    "isr",
    "israel",
    "it",
    "ita",
    "italia",
    "italian republic",
    "italy",
    "jam",
    "jamaica",
    "japan",
    "je",
    "jersey",
    "jey",
    "jm",
    "jo",
    "jor",
    "jordan",
    "jp",
    "jpn",
    "kaz",
    "kazakhstan",
    "ke",
    "ken",
    "kenya",
    "kg",
    "kgz",
    "kh",
    "khm",
    "ki",
    "kingdom of bahrain",
    "kingdom of belgium",
    "kingdom of bhutan",
    "kingdom of cambodia",
    "kingdom of denmark",
    "kingdom of eswatini",
    "kingdom of lesotho",
    "kingdom of morocco",
    "kingdom of norway",
    "kingdom of saudi arabia",
    "kingdom of spain",
    "kingdom of sweden",
    "kingdom of thailand",
    "kingdom of the netherlands",
    "kingdom of tonga",
    "kir",
    "kiribati",
    "km",
    "kn",
    "kna",
    "kor",
    "korea",
    "korea (democratic people's republic of)",
    "korea (democratic people´s republic of)",
    "korea (republic of (south korea))",
    "korea (republic of)",
    "korea (republic of, south korea)",
    "korea (south)",
    "korea (the democratic people's republic of)",
    "korea (the democratic people´s republic of)",
    "korea (the republic of)",
    "korea republic of (south korea)",
    "korea republic of, south korea",
    "korea, democratic people's republic of",
    "korea, democratic people´s republic of",
    "korea, republic of",
    "korea, republic of (south korea)",
    "korea, republic of, south korea",
    "korea, south",
    "korea, the democratic people's republic of",
    "korea, the democratic people´s republic of",
    "korea, the republic of",
    "kosovo",
    "kp",
    "kr",
    "kuwait",
    "kw",
    "kwt",
    "ky",
    "kyrgyz republic",
    "kyrgyzstan",
    "kz",
    "la",
    "lao",
    "lao people's democratic republic",
    "lao people's democratic republic (the)",
    "lao people's democratic republic, the",
    "lao people´s democratic republic",
    "lao people´s democratic republic (the)",
    "lao people´s democratic republic, the",
    "laos",
    "latvia",
    "lb",
    "lbn",
    "lbr",
    "lby",
    "lc",
    "lca",
    "lebanese republic",
    "lebanon",
    "lesotho",
    "li",
    "liberia",
    "libya",
    "lie",
    "liechtenstein",
    "lithuania",
    "lituania",
    "lk",
    "lka",
    "lr",
    "ls",
    "lso",
    "lt",
    "ltu",
    "lu",
    "lux",
    "luxembourg",
    "lv",
    "lva",
    "ly",
    "ma",
    "mac",
    "macao",
    "macao special administrative region of china",
    "macau",
    "macedonia",
    "macedonia (fyrom)",
    "macedonia (the former yugoslav republic of)",
    "macedonia, fyrom",
    "macedonia, the former yugoslav republic of",
    "madagascar",
    "maf",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "mar",
    "marshall islands",
    "marshall islands (the)",
    "marshall islands, the",
    "martinique",
    "mauritania",
    "mauritius",
    "mayotte",
    "mc",
    "mco",
    "md",
    "mda",
    "mdg",
    "mdv",
    "me",
    "mex",
    "mexico",
    "mf",
    "mg",
    "mh",
    "mhl",
    "micronesia",
    "micronesia (fed. states of)",
    "micronesia (federated states of)",
    "micronesia, fed. states of",
    "micronesia, federated states of",
    "mk",
    "mkd",
    "ml",
    "mli",
    "mlt",
    "mm",
    "mmr",
    "mn",
    "mne",
    "mng",
    "mnp",
    "mo",
    "moldova",
    "moldova (republic of)",
    "moldova (the republic of)",
    "moldova republic of",
    "moldova, (republic of)",
    "moldova, republic of",
    "moldova, the republic of",
    "monaco",
    "mongolia",
    "montenegro",
    "montserrat",
    "morocco",
    "morocoo",
    "moz",
    "mozambique",
    "mp",
    "mq",
    "mr",
    "mrt",
    "ms",
    "msr",
    "mt",
    "mtq",
    "mu",
    "mus",
    "mv",
    "mw",
    "mwi",
    "mx",
    "my",
    "myanmar",
    "myanmar (burma)",
    "myanmar, burma",
    "mys",
    "myt",
    "mz",
    "na",
    "nam",
    "namibia",
    "nauru",
    "nc",
    "ncl",
    "ne",
    "nepal",
    "ner",
    "netherlands",
    "netherlands (the)",
    "netherlands, the",
    "new caledonia",
    "new zealand",
    "nf",
    "nfk",
    "ng",
    "nga",
    "ni",
    "nic",
    "nicaragua",
    "nicaragura",
    "niger",
    "niger (the)",
    "niger, the",
    "nigeria",
    "niu",
    "niue",
    "nl",
    "nld",
    "no",
    "nor",
    "norfolk island",
    "north korea",
    "north macedonia",
    "northern ireland",
    "northern mariana islands",
    "northern mariana islands (the)",
    "northern mariana islands, the",
    "norway",
    "np",
    "npl",
    "nr",
    "nru",
    "nu",
    "nz",
    "nzl",
    "om",
    "oman",
    "omn",
    "pa",
    "pak",
    "pakistan",
    "palau",
    "palestine (state of)",
    "palestine, state of",
    "pan",
    "panama",
    "papua new guinea",
    "paraguay",
    "pcn",
    "pe",
    "people's democratic republic of algeria",
    "people's republic of bangladesh",
    "people's republic of china",
    "people´s democratic republic of algeria",
    "people´s republic of bangladesh",
    "people´s republic of china",
    "per",
    "peru",
    "pf",
    "pg",
    "ph",
    "philippines",
    "philippines (the)",
    "philippines, the",
    "phl",
    "pitcairn",
    "pk",
    "pl",
    "plurinational state of bolivia",
    "plw",
    "pm",
    "pn",
    "png",
    "pol",
    "poland",
    "portugal",
    "portuguese republic",
    "pr",
    "pri",
    "principality of andorra",
    "principality of liechtenstein",
    "principality of monaco",
    "prk",
    "prt",
    "pry",
    "ps",
    "pse",
    "pt",
    "puerto rico",
    "pw",
    "py",
    "pyf",
    "qa",
    "qat",
    "qatar",
    "re",
    "republic of albania",
    "republic of angola",
    "republic of armenia",
    "republic of austria",
    "republic of azerbaijan",
    "republic of belarus",
    "republic of benin",
    "republic of bosnia & herzegovina",
    "republic of bosnia and herzegovina",
    "republic of botswana",
    "republic of bulgaria",
    "republic of burundi",
    "republic of cabo verde",
    "republic of cameroon",
    "republic of chad",
    "republic of chile",
    "republic of colombia",
    "republic of costa rica",
    "republic of croatia",
    "republic of cuba",
    "republic of cyprus",
    "republic of côte d'ivoire",
    "republic of côte d´ivoire",
    "republic of djibouti",
    "republic of ecuador",
    "republic of el salvador",
    "republic of equatorial guinea",
    "republic of estonia",
    "republic of fiji",
    "republic of finland",
    "republic of ghana",
    "republic of guatemala",
    "republic of guinea",
    "republic of guinea-bissau",
    "republic of guyana",
    "republic of haiti",
    "republic of honduras",
    "republic of iceland",
    "republic of india",
    "republic of indonesia",
    "republic of iraq",
    "republic of kazakhstan",
    "republic of kenya",
    "republic of kiribati",
    "republic of korea",
    "republic of latvia",
    "republic of liberia",
    "republic of lithuania",
    "republic of madagascar",
    "republic of malawi",
    "republic of maldives",
    "republic of mali",
    "republic of malta",
    "republic of mauritius",
    "republic of moldova",
    "republic of mozambique",
    "republic of myanmar",
    "republic of namibia",
    "republic of nauru",
    "republic of nicaragua",
    "republic of north macedonia",
    "republic of palau",
    "republic of panama",
    "republic of paraguay",
    "republic of peru",
    "republic of poland",
    "republic of san marino",
    "republic of senegal",
    "republic of serbia",
    "republic of seychelles",
    "republic of sierra leone",
    "republic of singapore",
    "republic of slovenia",
    "republic of south africa",
    "republic of south sudan",
    "republic of suriname",
    "republic of tajikistan",
    "republic of the congo",
    "republic of the gambia",
    "republic of the marshall islands",
    "republic of the niger",
    "republic of the philippines",
    "republic of the sudan",
    "republic of trinidad & tobago",
    "republic of trinidad and tobago",
    "republic of tunisia",
    "republic of turkey",
    "republic of uganda",
    "republic of uzbekistan",
    "republic of vanuatu",
    "republic of yemen",
    "republic of zambia",
    "republic of zimbabwe",
    "reu",
    "reunion",
    "ro",
    "romania",
    "rou",
    "rs",
    "ru",
    "rus",
    "russia",
    "russian federation",
    "russian federation (the)",
    "russian federation, the",
    "rw",
    "rwa",
    "rwanda",
    "rwandese republic",
    "réunion",
    "sa",
    "saint barthelemy",
    "saint barthélemy",
    "saint helena",
    "saint helena (ascension & tristan da cunha)",
    "saint helena (ascension and tristan da cunha)",
    "saint helena, ascension & tristan da cunha",
    "saint helena, ascension and tristan da cunha",
    "saint kitts & nevis",
    "saint kitts and nevis",
    "saint lucia",
    "saint martin",
    "saint martin (french part)",
    "saint martin, french part",
    "saint pierre & miquelon",
    "saint pierre and miquelon",
    "saint vincent & the grenadines",
    "saint vincent and the grenadines",
    "samoa",
    "san marino",
    "sao tome & principe",
    "sao tome & principe,sao tome & principe",
    "sao tome and principe",
    "sao tome and principe,sao tome and principe",
    "sau",
    "saudi arabia",
    "sb",
    "sc",
    "scotland",
    "sd",
    "sdn",
    "se",
    "sen",
    "senegal",
    "serbia",
    "seychelles",
    "sg",
    "sgp",
    "sgs",
    "sh",
    "shn",
    "si",
    "sierra leone",
    "singapore",
    "sint maarten",
    "sint maarten (dutch part)",
    "sint maarten, dutch part",
    "sj",
    "sjm",
    "sk",
    "sl",
    "slb",
    "sle",
    "slovak republic",
    "slovakia",
    "slovenia",
    "slv",
    "sm",
    "smr",
    "sn",
    "so",
    "socialist republic of viet nam",
    "solomon islands",
    "som",
    "somalia",
    "south africa",
    "south georgia",
    "south georgia & the south s&wich isl&s",
    "south georgia and the south sandwich islands",
    "south korea",
    "south sudan",
    "spain",
    "spanien",
    "spm",
    "sr",
    "srb",
    "sri lanka",
    "ss",
    "ssd",
    "st",
    "state of israel",
    "state of kuwait",
    "state of palestine",
    "state of qatar",
    "stp",
    "sudan",
    "sudan (the)",
    "sudan, the",
    "sultanate of oman",
    "sur",
    "suriname",
    "sv",
    "svalbard & jan mayen",
    "svalbard and jan mayen",
    "svk",
    "svn",
    "swaziland",
    "swe",
    "sweden",
    "swiss confederation",
    "switzerland",
    "swz",
    "sx",
    "sxm",
    "sy",
    "syc",
    "syr",
    "syria",
    "syrian arab republic",
    "sz",
    "taiwan",
    "taiwan (province of china)",
    "taiwan*",
    "taiwan, province of china",
    "tajikistan",
    "tanzania",
    "tanzania (united republic of)",
    "tanzania, united republic of",
    "tc",
    "tca",
    "tcd",
    "td",
    "tf",
    "tg",
    "tgo",
    "th",
    "tha",
    "thailand",
    "the bahamas",
    "the former yugoslav republic of macedonia",
    "the netherlands",
    "the people's republic of china",
    "the people´s republic of china",
    "the state of eritrea",
    "the state of palestine",
    "timor-leste",
    "tj",
    "tjk",
    "tk",
    "tkl",
    "tkm",
    "tl",
    "tls",
    "tm",
    "tn",
    "to",
    "togo",
    "togolese republic",
    "tokelau",
    "ton",
    "tonga",
    "tr",
    "trinidad & tobago",
    "trinidad and tobago",
    "tschechien",
    "tt",
    "tto",
    "tun",
    "tunisia",
    "tur",
    "turkey",
    "turkmenistan",
    "turks & caicos isl&s",
    "turks & caicos isl&s (the)",
    "turks & caicos isl&s, the",
    "turks and caicos islands",
    "turks and caicos islands (the)",
    "turks and caicos islands, the",
    "tuv",
    "tuvalu",
    "tv",
    "tw",
    "twn",
    "tz",
    "tza",
    "ua",
    "uae",
    "ug",
    "uga",
    "uganda",
    "uk",
    "ukr",
    "ukraine",
    "um",
    "umi",
    "ungheria",
    "union of the comoros",
    "united arab emirates",
    "united arab emirates (the)",
    "united arab emirates, the",
    "united kingdom",
    "united kingdom of great britain & northern irel&",
    "united kingdom of great britain & northern irel& (the)",
    "united kingdom of great britain & northern irel&, the",
    "united kingdom of great britain and northern ireland",
    "united kingdom of great britain and northern ireland (the)",
    "united kingdom of great britain and northern ireland, the",
    "united mexican states",
    "united republic of tanzania",
    "united states",
    "united states minor outlying islands",
    "united states of america",
    "united states of america (the)",
    "united states of america, the",
    "united states virgin islands",
    "uruguay",
    "ury",
    "us",
    "us",
    "usa",
    "uy",
    "uz",
    "uzb",
    "uzbekistan",
    "va",
    "vanuatu",
    "vat",
    "vatican",
    "vatican city",
    "vc",
    "vct",
    "ve",
    "ven",
    "venezuela",
    "venezuela (bolivarian republic of)",
    "venezuela, bolivarian republic of",
    "vg",
    "vgb",
    "vi",
    "viet nam",
    "vietnam",
    "vir",
    "virgin islands (british)",
    "virgin islands (u.s.)",
    "virgin islands of the united states",
    "virgin islands, british",
    "virgin islands, u.s.",
    "vn",
    "vnm",
    "vu",
    "vut",
    "wales",
    "wallis & futuna",
    "wallis & futuna isl&s",
    "wallis and futuna",
    "wallis and futuna islands",
    "west bank & gaza",
    "west bank and gaza",
    "western sahara",
    "wf",
    "wlf",
    "ws",
    "wsm",
    "xk",
    "ye",
    "yem",
    "yemen",
    "yt",
    "za",
    "zaf",
    "zambia",
    "zimbabwe",
    "zm",
    "zmb",
    "zw",
    "zwe",
    "ål& isl&s",
    "åland islands",
    "türki̇ye",
    "türkiye",
    "turkiye",
    "turki̇ye",
]

COUNTRY_CODES = {
    "abw": "AW",
    "afg": "AF",
    "afghanistan": "AF",
    "ago": "AO",
    "aia": "AI",
    "ala": "AX",
    "alb": "AL",
    "albania": "AL",
    "algeria": "DZ",
    "american samoa": "AS",
    "and": "AD",
    "andorra": "AD",
    "angola": "AO",
    "anguilla": "AI",
    "antarctica": "AQ",
    "antigua": "AG",
    "antigua & barbuda": "AG",
    "antigua and barbuda": "AG",
    "arab republic of egypt": "EG",
    "are": "AE",
    "arg": "AR",
    "argentina": "AR",
    "argentine republic": "AR",
    "arm": "AM",
    "armenia": "AM",
    "aruba": "AW",
    "asm": "AS",
    "ata": "AQ",
    "atf": "TF",
    "atg": "AG",
    "aus": "AU",
    "australia": "AU",
    "austria": "AT",
    "aut": "AT",
    "aze": "AZ",
    "azerbaijan": "AZ",
    "bahamas": "BS",
    "bahamas (the)": "BS",
    "bahamas, the": "BS",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "barbuda": "AG",
    "bdi": "BI",
    "bel": "BE",
    "belarus": "BY",
    "belgium": "BE",
    "belize": "BZ",
    "ben": "BJ",
    "benin": "BJ",
    "bermuda": "BM",
    "bes": "BQ",
    "bfa": "BF",
    "bgd": "BD",
    "bgr": "BG",
    "bhr": "BH",
    "bhs": "BS",
    "bhutan": "BT",
    "bih": "BA",
    "blm": "BL",
    "blr": "BY",
    "blz": "BZ",
    "bmu": "BM",
    "bol": "BO",
    "bolivarian republic of venezuela": "VE",
    "bolivia": "BO",
    "bolivia (plurinational state of)": "BO",
    "bolivia, plurinational state of": "BO",
    "bonaire (sint eustatius & saba)": "BQ",
    "bonaire (sint eustatius and saba)": "BQ",
    "bonaire, sint eustatius & saba": "BQ",
    "bonaire, sint eustatius and saba": "BQ",
    "bosnia": "BA",
    "bosnia & herzegovina": "BA",
    "bosnia and herzegovina": "BA",
    "botswana": "BW",
    "bouvet island": "BV",
    "bra": "BR",
    "brazil": "BR",
    "brb": "BB",
    "britain": "GB",
    "british indian ocean territory": "IO",
    "british virgin islands": "VG",
    "brn": "BN",
    "brunei": "BN",
    "brunei darussalam": "BN",
    "btn": "BT",
    "bulgaria": "BG",
    "burkina faso": "BF",
    "burma": "MM",
    "burundi": "BI",
    "bvt": "BV",
    "bwa": "BW",
    "cabo verde": "CV",
    "caf": "CF",
    "cambodia": "KH",
    "cameroon": "CM",
    "can": "CA",
    "canada": "CA",
    "cape verde": "CV",
    "cayman islands": "KY",
    "cayman islands (the)": "KY",
    "cayman islands, the": "KY",
    "cck": "CC",
    "central african republic": "CF",
    "central african republic (the)": "CF",
    "central african republic, the": "CF",
    "chad": "TD",
    "channel islands": "GB",
    "che": "CH",
    "chile": "CL",
    "china": "CN",
    "china (hong kong sar)": "HK",
    "china (macao sar)": "MO",
    "china (taiwan province of china)": "TW",
    "china, hong kong sar": "HK",
    "china, macao sar": "MO",
    "china, taiwan province of china": "TW",
    "chl": "CL",
    "chn": "CN",
    "christmas island": "CX",
    "civ": "CI",
    "cmr": "CM",
    "cocos (keeling) islands": "CC",
    "cod": "CD",
    "cog": "CG",
    "cok": "CK",
    "col": "CO",
    "colombia": "CO",
    "com": "KM",
    "commonwealth of dominica": "DM",
    "commonwealth of the bahamas": "BS",
    "commonwealth of the northern mariana islands": "MP",
    "comoros": "KM",
    "comoros (the)": "KM",
    "comoros, the": "KM",
    "congo": "CG",
    "congo (brazzaville)": "CD",
    "congo (democratic republic of the)": "CD",
    "congo (kinshasa)": "CG",
    "congo (the democratic republic of the)": "CD",
    "congo (the)": "CG",
    "congo, brazzaville": "CD",
    "congo, democratic republic of the": "CD",
    "congo, kinshasa": "CG",
    "congo, the": "CG",
    "congo, the democratic republic of the": "CD",
    "cook islands": "CK",
    "cook islands (the)": "CK",
    "cook islands, the": "CK",
    "costa rica": "CR",
    "cote d'ivoire": "CI",
    "cote d\u00b4ivoire": "CI",
    "cpv": "CV",
    "cri": "CR",
    "croatia": "HR",
    "cub": "CU",
    "cuba": "CU",
    "curacao": "CW",
    "cura\u00e7ao": "CW",
    "cuw": "CW",
    "cxr": "CX",
    "cym": "KY",
    "cyp": "CY",
    "cyprus": "CY",
    "cze": "CZ",
    "czech": "CZ",
    "czech republic": "CZ",
    "czechia": "CZ",
    "czechia (czech republic)": "CZ",
    "czechia, czech republic": "CZ",
    "c\u00f4te d'ivoire": "CI",
    "c\u00f4te d\u00b4ivoire": "CI",
    "dem. people's republic of korea": "KP",
    "dem. people\u00b4s republic of korea": "KP",
    "democratic people's republic of korea": "KP",
    "democratic people\u00b4s republic of korea": "KP",
    "democratic republic of sao tome & principe": "ST",
    "democratic republic of sao tome and principe": "ST",
    "democratic republic of the congo": "CD",
    "democratic republic of timor-leste": "TL",
    "democratic socialist republic of sri lanka": "LK",
    "denmark": "DK",
    "deu": "DE",
    "dji": "DJ",
    "djibouti": "DJ",
    "dma": "DM",
    "dnk": "DK",
    "dom": "DO",
    "dominica": "DM",
    "dominican republic": "DO",
    "dominican republic (the)": "DO",
    "dominican republic, the": "DO",
    "dza": "DZ",
    "d\u00e4nemark": "DK",
    "eastern republic of uruguay": "UY",
    "ecu": "EC",
    "ecuador": "EC",
    "egy": "EG",
    "egypt": "EG",
    "el salvador": "SV",
    "equatorial guinea": "GQ",
    "eri": "ER",
    "eritrea": "ER",
    "esh": "EH",
    "esp": "ES",
    "est": "EE",
    "estonia": "EE",
    "eswatini": "SZ",
    "eth": "ET",
    "ethiopia": "ET",
    "falkl& isl&s (malvinas)": "FK",
    "falkl& isl&s (the) [malvinas]": "FK",
    "falkl& isl&s, malvinas": "FK",
    "falkland islands (malvinas)": "FK",
    "falkland islands (the) [malvinas]": "FK",
    "falkland islands, malvinas": "FK",
    "faroe islands": "FO",
    "faroe islands (the)": "FO",
    "faroe islands, the": "FO",
    "federal democratic republic of ethiopia": "ET",
    "federal democratic republic of nepal": "NP",
    "federal republic of germany": "DE",
    "federal republic of nigeria": "NG",
    "federal republic of somalia": "SO",
    "federated states of micronesia": "FM",
    "federative republic of brazil": "BR",
    "fiji": "FJ",
    "fin": "FI",
    "finland": "FI",
    "fji": "FJ",
    "flk": "FK",
    "fra": "FR",
    "france": "FR",
    "french guiana": "GF",
    "french polynesia": "PF",
    "french republic": "FR",
    "french southern territories": "TF",
    "fro": "FO",
    "fsm": "FM",
    "gab": "GA",
    "gabon": "GA",
    "gabonese republic": "GA",
    "gambia": "GM",
    "gambia (the)": "GM",
    "gambia, the": "GM",
    "gbr": "GB",
    "geo": "GE",
    "georgia": "GE",
    "germany": "DE",
    "ggy": "GG",
    "gha": "GH",
    "ghana": "GH",
    "gib": "GI",
    "gibraltar": "GI",
    "gin": "GN",
    "glp": "GP",
    "gmb": "GM",
    "gnb": "GW",
    "gnq": "GQ",
    "gr& duchy of luxembourg": "LU",
    "grand duchy of luxembourg": "LU",
    "grc": "GR",
    "grd": "GD",
    "great britain": "GB",
    "greece": "GR",
    "greenland": "GL",
    "grenada": "GD",
    "grl": "GL",
    "gtm": "GT",
    "guadeloupe": "GP",
    "guam": "GU",
    "guatemala": "GT",
    "guernsey": "GG",
    "guf": "GF",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "gum": "GU",
    "guy": "GY",
    "guyana": "GY",
    "haiti": "HT",
    "hashemite kingdom of jordan": "JO",
    "heard isl& & mcdonald isl&s": "HM",
    "heard island and mcdonald islands": "HM",
    "hellenic republic": "GR",
    "herzegovina": "BA",
    "hkg": "HK",
    "hmd": "HM",
    "hnd": "HN",
    "holland": "NL",
    "holy see": "VA",
    "holy see (the)": "VA",
    "holy see (vatican city state)": "VA",
    "holy see, the": "VA",
    "holy see, vatican city state": "VA",
    "honduras": "HN",
    "hong kong": "HK",
    "hong kong (china (sar))": "HK",
    "hong kong (china)": "HK",
    "hong kong (china, sar)": "HK",
    "hong kong sar": "HK",
    "hong kong special administrative region of china": "HK",
    "hong kong, china": "HK",
    "hong kong, china (sar)": "HK",
    "hong kong, china, sar": "HK",
    "hrv": "HR",
    "hti": "HT",
    "hun": "HU",
    "hungary": "HU",
    "iceland": "IS",
    "idn": "ID",
    "imn": "IM",
    "ind": "IN",
    "independent state of papua new guinea": "PG",
    "independent state of samoa": "WS",
    "india": "IN",
    "indonega": "ID",
    "indonesia": "ID",
    "iot": "IO",
    "iran": "IR",
    "iran (islamic republic of)": "IR",
    "iran, islamic republic of": "IR",
    "iraq": "IQ",
    "ireland": "IE",
    "irl": "IE",
    "irn": "IR",
    "irq": "IQ",
    "isl": "IS",
    "islamic republic of afghanistan": "AF",
    "islamic republic of iran": "IR",
    "islamic republic of mauritania": "MR",
    "islamic republic of pakistan": "PK",
    "isle of man": "IM",
    "isr": "IL",
    "israel": "IL",
    "ita": "IT",
    "italia": "IT",
    "italian republic": "IT",
    "italy": "IT",
    "jam": "JM",
    "jamaica": "JM",
    "japan": "JP",
    "jersey": "JE",
    "jey": "JE",
    "jor": "JO",
    "jordan": "JO",
    "jpn": "JP",
    "kaz": "KZ",
    "kazakhstan": "KZ",
    "ken": "KE",
    "kenya": "KE",
    "kgz": "KG",
    "khm": "KH",
    "kingdom of bahrain": "BH",
    "kingdom of belgium": "BE",
    "kingdom of bhutan": "BT",
    "kingdom of cambodia": "KH",
    "kingdom of denmark": "DK",
    "kingdom of eswatini": "SZ",
    "kingdom of lesotho": "LS",
    "kingdom of morocco": "MA",
    "kingdom of norway": "NO",
    "kingdom of saudi arabia": "SA",
    "kingdom of spain": "ES",
    "kingdom of sweden": "SE",
    "kingdom of thailand": "TH",
    "kingdom of the netherlands": "NL",
    "kingdom of tonga": "TO",
    "kir": "KI",
    "kiribati": "KI",
    "kna": "KN",
    "kor": "KR",
    "korea": "KR",
    "korea (democratic people's republic of)": "KP",
    "korea (democratic people\u00b4s republic of)": "KP",
    "korea (republic of (south korea))": "KR",
    "korea (republic of)": "KR",
    "korea (republic of, south korea)": "KR",
    "korea (south)": "KR",
    "korea (the democratic people's republic of)": "KP",
    "korea (the democratic people\u00b4s republic of)": "KP",
    "korea (the republic of)": "KR",
    "korea republic of (south korea)": "KR",
    "korea republic of, south korea": "KR",
    "korea, democratic people's republic of": "KP",
    "korea, democratic people\u00b4s republic of": "KP",
    "korea, republic of": "KR",
    "korea, republic of (south korea)": "KR",
    "korea, republic of, south korea": "KR",
    "korea, south": "KR",
    "korea, the democratic people's republic of": "KP",
    "korea, the democratic people\u00b4s republic of": "KP",
    "korea, the republic of": "KR",
    "kosovo": "XK",
    "kuwait": "KW",
    "kwt": "KW",
    "kyrgyz republic": "KG",
    "kyrgyzstan": "KG",
    "lao": "LA",
    "lao people's democratic republic": "LA",
    "lao people's democratic republic (the)": "LA",
    "lao people's democratic republic, the": "LA",
    "lao people\u00b4s democratic republic": "LA",
    "lao people\u00b4s democratic republic (the)": "LA",
    "lao people\u00b4s democratic republic, the": "LA",
    "laos": "LA",
    "latvia": "LV",
    "lbn": "LB",
    "lbr": "LR",
    "lby": "LY",
    "lca": "LC",
    "lebanese republic": "LB",
    "lebanon": "LB",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "lie": "LI",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "lituania": "LT",
    "lka": "LK",
    "lso": "LS",
    "ltu": "LT",
    "lux": "LU",
    "luxembourg": "LU",
    "lva": "LV",
    "mac": "MO",
    "macao": "MO",
    "macao special administrative region of china": "MO",
    "macau": "MO",
    "macedonia": "MK",
    "macedonia (fyrom)": "MK",
    "macedonia (the former yugoslav republic of)": "MK",
    "macedonia, fyrom": "MK",
    "macedonia, the former yugoslav republic of": "MK",
    "madagascar": "MG",
    "maf": "MF",
    "malawi": "MW",
    "malaysia": "MY",
    "maldives": "MV",
    "mali": "ML",
    "malta": "MT",
    "mar": "MA",
    "marshall islands": "MH",
    "marshall islands (the)": "MH",
    "marshall islands, the": "MH",
    "martinique": "MQ",
    "mauritania": "MR",
    "mauritius": "MU",
    "mayotte": "YT",
    "mco": "MC",
    "mda": "MD",
    "mdg": "MG",
    "mdv": "MV",
    "mex": "MX",
    "mexico": "MX",
    "mhl": "MH",
    "micronesia": "FM",
    "micronesia (fed. states of)": "FM",
    "micronesia (federated states of)": "FM",
    "micronesia, fed. states of": "FM",
    "micronesia, federated states of": "FM",
    "mkd": "MK",
    "mli": "ML",
    "mlt": "MT",
    "mmr": "MM",
    "mne": "ME",
    "mng": "MN",
    "mnp": "MP",
    "moldova": "MD",
    "moldova (republic of)": "MD",
    "moldova (the republic of)": "MD",
    "moldova republic of": "MD",
    "moldova, (republic of)": "MD",
    "moldova, republic of": "MD",
    "moldova, the republic of": "MD",
    "monaco": "MC",
    "mongolia": "MN",
    "montenegro": "ME",
    "montserrat": "MS",
    "morocco": "MA",
    "morocoo": "MA",
    "moz": "MZ",
    "mozambique": "MZ",
    "mrt": "MR",
    "msr": "MS",
    "mtq": "MQ",
    "mus": "MU",
    "mwi": "MW",
    "myanmar": "MM",
    "myanmar (burma)": "MM",
    "myanmar, burma": "MM",
    "mys": "MY",
    "myt": "YT",
    "nam": "NA",
    "namibia": "NA",
    "nauru": "NR",
    "ncl": "NC",
    "nepal": "NP",
    "ner": "NE",
    "netherlands": "NL",
    "netherlands (the)": "NL",
    "netherlands, the": "NL",
    "new caledonia": "NC",
    "new zealand": "NZ",
    "nfk": "NF",
    "nga": "NG",
    "nic": "NI",
    "nicaragua": "NI",
    "nicaragura": "NI",
    "niger": "NE",
    "niger (the)": "NE",
    "niger, the": "NE",
    "nigeria": "NG",
    "niu": "NU",
    "niue": "NU",
    "nld": "NL",
    "nor": "NO",
    "norfolk island": "NF",
    "north korea": "KP",
    "north macedonia": "MK",
    "northern ireland": "GB",
    "northern mariana islands": "MP",
    "northern mariana islands (the)": "MP",
    "northern mariana islands, the": "MP",
    "norway": "NO",
    "npl": "NP",
    "nru": "NR",
    "nzl": "NZ",
    "oman": "OM",
    "omn": "OM",
    "pak": "PK",
    "pakistan": "PK",
    "palau": "PW",
    "palestine (state of)": "PS",
    "palestine, state of": "PS",
    "pan": "PA",
    "panama": "PA",
    "papua new guinea": "PG",
    "paraguay": "PY",
    "pcn": "PN",
    "people's democratic republic of algeria": "DZ",
    "people's republic of bangladesh": "BD",
    "people's republic of china": "CN",
    "people\u00b4s democratic republic of algeria": "DZ",
    "people\u00b4s republic of bangladesh": "BD",
    "people\u00b4s republic of china": "CN",
    "per": "PE",
    "peru": "PE",
    "philippines": "PH",
    "philippines (the)": "PH",
    "philippines, the": "PH",
    "phl": "PH",
    "pitcairn": "PN",
    "plurinational state of bolivia": "BO",
    "plw": "PW",
    "png": "PG",
    "pol": "PL",
    "poland": "PL",
    "portugal": "PT",
    "portuguese republic": "PT",
    "pri": "PR",
    "principality of andorra": "AD",
    "principality of liechtenstein": "LI",
    "principality of monaco": "MC",
    "prk": "KP",
    "prt": "PT",
    "pry": "PY",
    "pse": "PS",
    "puerto rico": "PR",
    "pyf": "PF",
    "qat": "QA",
    "qatar": "QA",
    "republic of albania": "AL",
    "republic of angola": "AO",
    "republic of armenia": "AM",
    "republic of austria": "AT",
    "republic of azerbaijan": "AZ",
    "republic of belarus": "BY",
    "republic of benin": "BJ",
    "republic of bosnia & herzegovina": "BA",
    "republic of bosnia and herzegovina": "BA",
    "republic of botswana": "BW",
    "republic of bulgaria": "BG",
    "republic of burundi": "BI",
    "republic of cabo verde": "CV",
    "republic of cameroon": "CM",
    "republic of chad": "TD",
    "republic of chile": "CL",
    "republic of colombia": "CO",
    "republic of costa rica": "CR",
    "republic of croatia": "HR",
    "republic of cuba": "CU",
    "republic of cyprus": "CY",
    "republic of c\u00f4te d'ivoire": "CI",
    "republic of c\u00f4te d\u00b4ivoire": "CI",
    "republic of djibouti": "DJ",
    "republic of ecuador": "EC",
    "republic of el salvador": "SV",
    "republic of equatorial guinea": "GQ",
    "republic of estonia": "EE",
    "republic of fiji": "FJ",
    "republic of finland": "FI",
    "republic of ghana": "GH",
    "republic of guatemala": "GT",
    "republic of guinea": "GN",
    "republic of guinea-bissau": "GW",
    "republic of guyana": "GY",
    "republic of haiti": "HT",
    "republic of honduras": "HN",
    "republic of iceland": "IS",
    "republic of india": "IN",
    "republic of indonesia": "ID",
    "republic of iraq": "IQ",
    "republic of kazakhstan": "KZ",
    "republic of kenya": "KE",
    "republic of kiribati": "KI",
    "republic of korea": "KR",
    "republic of latvia": "LV",
    "republic of liberia": "LR",
    "republic of lithuania": "LT",
    "republic of madagascar": "MG",
    "republic of malawi": "MW",
    "republic of maldives": "MV",
    "republic of mali": "ML",
    "republic of malta": "MT",
    "republic of mauritius": "MU",
    "republic of moldova": "MD",
    "republic of mozambique": "MZ",
    "republic of myanmar": "MM",
    "republic of namibia": "NA",
    "republic of nauru": "NR",
    "republic of nicaragua": "NI",
    "republic of north macedonia": "MK",
    "republic of palau": "PW",
    "republic of panama": "PA",
    "republic of paraguay": "PY",
    "republic of peru": "PE",
    "republic of poland": "PL",
    "republic of san marino": "SM",
    "republic of senegal": "SN",
    "republic of serbia": "RS",
    "republic of seychelles": "SC",
    "republic of sierra leone": "SL",
    "republic of singapore": "SG",
    "republic of slovenia": "SI",
    "republic of south africa": "ZA",
    "republic of south sudan": "SS",
    "republic of suriname": "SR",
    "republic of tajikistan": "TJ",
    "republic of the congo": "CG",
    "republic of the gambia": "GM",
    "republic of the marshall islands": "MH",
    "republic of the niger": "NE",
    "republic of the philippines": "PH",
    "republic of the sudan": "SD",
    "republic of trinidad & tobago": "TT",
    "republic of trinidad and tobago": "TT",
    "republic of tunisia": "TN",
    "republic of turkey": "TR",
    "republic of uganda": "UG",
    "republic of uzbekistan": "UZ",
    "republic of vanuatu": "VU",
    "republic of yemen": "YE",
    "republic of zambia": "ZM",
    "republic of zimbabwe": "ZW",
    "reu": "RE",
    "reunion": "RE",
    "romania": "RO",
    "rou": "RO",
    "rus": "RU",
    "russia": "RU",
    "russian federation": "RU",
    "russian federation (the)": "RU",
    "russian federation, the": "RU",
    "rwa": "RW",
    "rwanda": "RW",
    "rwandese republic": "RW",
    "r\u00e9union": "RE",
    "saint barthelemy": "BL",
    "saint barth\u00e9lemy": "BL",
    "saint helena": "SH",
    "saint helena (ascension & tristan da cunha)": "SH",
    "saint helena (ascension and tristan da cunha)": "SH",
    "saint helena, ascension & tristan da cunha": "SH",
    "saint helena, ascension and tristan da cunha": "SH",
    "saint kitts & nevis": "KN",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "saint martin": "MF",
    "saint martin (french part)": "MF",
    "saint martin, french part": "MF",
    "saint pierre & miquelon": "PM",
    "saint pierre and miquelon": "PM",
    "saint vincent & the grenadines": "VC",
    "saint vincent and the grenadines": "VC",
    "samoa": "WS",
    "san marino": "SM",
    "sao tome & principe": "ST",
    "sao tome & principe,sao tome & principe": "ST",
    "sao tome and principe": "ST",
    "sao tome and principe,sao tome and principe": "ST",
    "sau": "SA",
    "saudi arabia": "SA",
    "scotland": "GB",
    "sdn": "SD",
    "sen": "SN",
    "senegal": "SN",
    "serbia": "RS",
    "seychelles": "SC",
    "sgp": "SG",
    "sgs": "GS",
    "shn": "SH",
    "sierra leone": "SL",
    "singapore": "SG",
    "sint maarten": "SX",
    "sint maarten (dutch part)": "SX",
    "sint maarten, dutch part": "SX",
    "sjm": "SJ",
    "slb": "SB",
    "sle": "SL",
    "slovak republic": "SK",
    "slovakia": "SK",
    "slovenia": "SI",
    "slv": "SV",
    "smr": "SM",
    "socialist republic of viet nam": "VN",
    "solomon islands": "SB",
    "som": "SO",
    "somalia": "SO",
    "south africa": "ZA",
    "south georgia": "GS",
    "south georgia & the south s&wich isl&s": "GS",
    "south georgia and the south sandwich islands": "GS",
    "south korea": "KR",
    "south sudan": "SS",
    "spain": "ES",
    "spanien": "ES",
    "spm": "PM",
    "srb": "RS",
    "sri lanka": "LK",
    "ssd": "SS",
    "state of israel": "IL",
    "state of kuwait": "KW",
    "state of palestine": "PS",
    "state of qatar": "QA",
    "stp": "ST",
    "sudan": "SD",
    "sudan (the)": "SD",
    "sudan, the": "SD",
    "sultanate of oman": "OM",
    "sur": "SR",
    "suriname": "SR",
    "svalbard & jan mayen": "SJ",
    "svalbard and jan mayen": "SJ",
    "svk": "SK",
    "svn": "SI",
    "swaziland": "SZ",
    "swe": "SE",
    "sweden": "SE",
    "swiss confederation": "CH",
    "switzerland": "CH",
    "swz": "SZ",
    "sxm": "SX",
    "syc": "SC",
    "syr": "SY",
    "syria": "SY",
    "syrian arab republic": "SY",
    "taiwan": "TW",
    "taiwan (province of china)": "TW",
    "taiwan*": "TW",
    "taiwan, province of china": "TW",
    "tajikistan": "TJ",
    "tanzania": "TZ",
    "tanzania (united republic of)": "TZ",
    "tanzania, united republic of": "TZ",
    "tca": "TC",
    "tcd": "TD",
    "tgo": "TG",
    "tha": "TH",
    "thailand": "TH",
    "the bahamas": "BS",
    "the former yugoslav republic of macedonia": "MK",
    "the netherlands": "NL",
    "the people's republic of china": "CN",
    "the people\u00b4s republic of china": "CN",
    "the state of eritrea": "ER",
    "the state of palestine": "PS",
    "timor-leste": "TL",
    "tjk": "TJ",
    "tkl": "TK",
    "tkm": "TM",
    "tls": "TL",
    "togo": "TG",
    "togolese republic": "TG",
    "tokelau": "TK",
    "ton": "TO",
    "tonga": "TO",
    "trinidad & tobago": "TT",
    "trinidad and tobago": "TT",
    "tschechien": "CZ",
    "tto": "TT",
    "tun": "TN",
    "tunisia": "TN",
    "tur": "TR",
    "turkey": "TR",
    "türki̇ye": "TR",
    # NOTE: The entry below not a duplicate. Unicode chars appear similar
    "türkiye": "TR",
    "turkiye": "TR",
    # NOTE: The entry below not a duplicate. Unicode chars appear similar
    "turki̇ye": "TR",
    "turkmenistan": "TM",
    "turks & caicos isl&s": "TC",
    "turks & caicos isl&s (the)": "TC",
    "turks & caicos isl&s, the": "TC",
    "turks and caicos islands": "TC",
    "turks and caicos islands (the)": "TC",
    "turks and caicos islands, the": "TC",
    "tuv": "TV",
    "tuvalu": "TV",
    "twn": "TW",
    "tza": "TZ",
    "uae": "AE",
    "uga": "UG",
    "uganda": "UG",
    "uk": "GB",
    "ukr": "UA",
    "ukraine": "UA",
    "umi": "UM",
    "ungheria": "HU",
    "union of the comoros": "KM",
    "united arab emirates": "AE",
    "united arab emirates (the)": "AE",
    "united arab emirates, the": "AE",
    "united kingdom": "GB",
    "united kingdom of great britain & northern irel&": "GB",
    "united kingdom of great britain & northern irel& (the)": "GB",
    "united kingdom of great britain & northern irel&, the": "GB",
    "united kingdom of great britain and northern ireland": "GB",
    "united kingdom of great britain and northern ireland (the)": "GB",
    "united kingdom of great britain and northern ireland, the": "GB",
    "united mexican states": "MX",
    "united republic of tanzania": "TZ",
    "united states": "US",
    "united states minor outlying islands": "UM",
    "united states of america": "US",
    "united states of america (the)": "US",
    "united states of america, the": "US",
    "united states virgin islands": "VI",
    "uruguay": "UY",
    "ury": "UY",
    "us": "US",
    "usa": "US",
    "uzb": "UZ",
    "uzbekistan": "UZ",
    "vanuatu": "VU",
    "vat": "VA",
    "vatican": "VA",
    "vatican city": "VA",
    "vct": "VC",
    "ven": "VE",
    "venezuela": "VE",
    "venezuela (bolivarian republic of)": "VE",
    "venezuela, bolivarian republic of": "VE",
    "vgb": "VG",
    "viet nam": "VN",
    "vietnam": "VN",
    "vir": "VI",
    "virgin islands (british)": "VG",
    "virgin islands (u.s.)": "VI",
    "virgin islands of the united states": "VI",
    "virgin islands, british": "VG",
    "virgin islands, u.s.": "VI",
    "vnm": "VN",
    "vut": "VU",
    "wales": "GB",
    "wallis & futuna": "WF",
    "wallis & futuna isl&s": "WF",
    "wallis and futuna": "WF",
    "wallis and futuna islands": "WF",
    "west bank & gaza": "PS",
    "west bank and gaza": "PS",
    "western sahara": "EH",
    "wlf": "WF",
    "wsm": "WS",
    "yem": "YE",
    "yemen": "YE",
    "zaf": "ZA",
    "zambia": "ZM",
    "zimbabwe": "ZW",
    "zmb": "ZM",
    "zwe": "ZW",
    "\u00e5l& isl&s": "AX",
    "\u00e5land islands": "AX",
    "sv": "SV",
    "im": "IM",
    "la": "LA",
    "nf": "NF",
    "hm": "HM",
    "cw": "CW",
    "as": "AS",
    "de": "DE",
    "sa": "SA",
    "mz": "MZ",
    "gh": "GH",
    "sb": "SB",
    "pk": "PK",
    "bq": "BQ",
    "pr": "PR",
    "mk": "MK",
    "hr": "HR",
    "mg": "MG",
    "cm": "CM",
    "cn": "CN",
    "bz": "BZ",
    "pa": "PA",
    "cl": "CL",
    "bt": "BT",
    "gm": "GM",
    "ec": "EC",
    "bs": "BS",
    "mf": "MF",
    "pn": "PN",
    "ck": "CK",
    "gl": "GL",
    "vu": "VU",
    "aw": "AW",
    "pm": "PM",
    "ax": "AX",
    "tj": "TJ",
    "lt": "LT",
    "sh": "SH",
    "ua": "UA",
    "kz": "KZ",
    "gp": "GP",
    "sg": "SG",
    "si": "SI",
    "om": "OM",
    "rs": "RS",
    "ug": "UG",
    "vc": "VC",
    "cz": "CZ",
    "fj": "FJ",
    "sz": "SZ",
    "ki": "KI",
    "ad": "AD",
    "sm": "SM",
    "au": "AU",
    "uy": "UY",
    "pg": "PG",
    "jp": "JP",
    "cr": "CR",
    "lv": "LV",
    "pl": "PL",
    "gb": "GB",
    "pw": "PW",
    "mc": "MC",
    "gt": "GT",
    "vg": "VG",
    "cv": "CV",
    "sc": "SC",
    "tr": "TR",
    "bb": "BB",
    "ky": "KY",
    "li": "LI",
    "wf": "WF",
    "et": "ET",
    "to": "TO",
    "gi": "GI",
    "na": "NA",
    "cx": "CX",
    "nl": "NL",
    "tm": "TM",
    "th": "TH",
    "dm": "DM",
    "fo": "FO",
    "mq": "MQ",
    "ps": "PS",
    "mr": "MR",
    "ag": "AG",
    "cf": "CF",
    "io": "IO",
    "dj": "DJ",
    "kp": "KP",
    "jo": "JO",
    "mw": "MW",
    "sy": "SY",
    "sl": "SL",
    "ir": "IR",
    "tc": "TC",
    "zm": "ZM",
    "bw": "BW",
    "cg": "CG",
    "fi": "FI",
    "ms": "MS",
    "vi": "VI",
    "va": "VA",
    "jm": "JM",
    "mh": "MH",
    "nr": "NR",
    "um": "UM",
    "cd": "CD",
    "ss": "SS",
    "bf": "BF",
    "mn": "MN",
    "am": "AM",
    "sr": "SR",
    "id": "ID",
    "nu": "NU",
    "sn": "SN",
    "ma": "MA",
    "ar": "AR",
    "nz": "NZ",
    "tz": "TZ",
    "no": "NO",
    "bi": "BI",
    "md": "MD",
    "il": "IL",
    "do": "DO",
    "ie": "IE",
    "kw": "KW",
    "td": "TD",
    "eg": "EG",
    "hn": "HN",
    "iq": "IQ",
    "nc": "NC",
    "gg": "GG",
    "mo": "MO",
    "my": "MY",
    "az": "AZ",
    "cu": "CU",
    "ly": "LY",
    "lc": "LC",
    "bh": "BH",
    "hu": "HU",
    "sx": "SX",
    "fm": "FM",
    "gw": "GW",
    "bm": "BM",
    "ba": "BA",
    "tf": "TF",
    "ca": "CA",
    "ci": "CI",
    "cy": "CY",
    "lu": "LU",
    "it": "IT",
    "lb": "LB",
    "pf": "PF",
    "re": "RE",
    "gy": "GY",
    "tg": "TG",
    "ch": "CH",
    "tl": "TL",
    "tv": "TV",
    "lk": "LK",
    "co": "CO",
    "kn": "KN",
    "tw": "TW",
    "gr": "GR",
    "tn": "TN",
    "rw": "RW",
    "py": "PY",
    "vn": "VN",
    "me": "ME",
    "mm": "MM",
    "tk": "TK",
    "km": "KM",
    "mp": "MP",
    "gf": "GF",
    "uz": "UZ",
    "gu": "GU",
    "lr": "LR",
    "kg": "KG",
    "al": "AL",
    "so": "SO",
    "gq": "GQ",
    "af": "AF",
    "bg": "BG",
    "dk": "DK",
    "ge": "GE",
    "yt": "YT",
    "ae": "AE",
    "mx": "MX",
    "tt": "TT",
    "zw": "ZW",
    "dz": "DZ",
    "ee": "EE",
    "za": "ZA",
    "bl": "BL",
    "is": "IS",
    "pe": "PE",
    "bd": "BD",
    "bo": "BO",
    "aq": "AQ",
    "ga": "GA",
    "ni": "NI",
    "ht": "HT",
    "kr": "KR",
    "ro": "RO",
    "qa": "QA",
    "se": "SE",
    "ye": "YE",
    "be": "BE",
    "by": "BY",
    "ve": "VE",
    "ls": "LS",
    "np": "NP",
    "bn": "BN",
    "xk": "XK",
    "ph": "PH",
    "sk": "SK",
    "in": "IN",
    "je": "JE",
    "br": "BR",
    "mt": "MT",
    "ng": "NG",
    "eh": "EH",
    "mu": "MU",
    "pt": "PT",
    "bv": "BV",
    "fr": "FR",
    "hk": "HK",
    "gd": "GD",
    "ke": "KE",
    "ne": "NE",
    "sd": "SD",
    "mv": "MV",
    "us": "US",
    "ml": "ML",
    "gs": "GS",
    "er": "ER",
    "ru": "RU",
    "kh": "KH",
    "fk": "FK",
    "st": "ST",
    "sj": "SJ",
    "cc": "CC",
    "ao": "AO",
    "ai": "AI",
    "at": "AT",
    "es": "ES",
    "bj": "BJ",
    "ws": "WS",
    "gn": "GN",
}

US_STATES = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
}

CAN_PROVINCES = {
    "ON": "Ontario",
    "QC": "Quebec",
    "NS": "Nova Scotia",
    "NB": "New Brunswick",
    "MB": "Manitoba",
    "BC": "British Columbia",
    "PE": "Prince Edward Island",
    "SK": "Saskatchewan",
    "AB": "Alberta",
    "NL": "Newfoundland and Labrador",
}
