#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

function usage() {
    echo -e \
    "Usage: $(basename "$0")" \
    "\nThis script starts up the local development environment with seeded" \
    "data in the database."
}

function setup_minio() {
  MINIO_ALIAS="dockerminio"
  MINIO_USER="minioadmin"
  MINIO_PASSWORD="minioadmin"
  echo "Setting up MinIO alias $MINIO_ALIAS..."
  docker compose exec minio bash \
          -c "mc alias set $MINIO_ALIAS http://minio:9000 $MINIO_USER $MINIO_PASSWORD"

  MINIO_BUCKET="os-hub-dev"
  echo "Creating MinIO bucket $MINIO_BUCKET..."
  docker compose exec minio bash -c "mc mb --ignore-existing $MINIO_ALIAS/$MINIO_BUCKET"


  echo "Copying fixtures to MinIO bucket $MINIO_BUCKET..."
  docker compose exec minio bash \
          -c "mkdir -p /fixtures"
  docker compose cp ./src/django/api/fixtures minio:/fixtures
  docker compose exec minio bash \
          -c "mc cp --recursive /fixtures/* $MINIO_ALIAS/$MINIO_BUCKET/api/"
  docker compose exec minio bash \
          -c "rm -rf /fixtures"

  TIGERLINE_CSV="us_county_tigerline_2025.csv"

  if [ -f "./src/django/$TIGERLINE_CSV" ]; then
    echo "Copying $TIGERLINE_CSV to MinIO bucket $MINIO_BUCKET..."
    docker compose exec minio bash \
          -c "mkdir -p /temp"
    docker compose cp ./src/django/$TIGERLINE_CSV minio:/temp/$TIGERLINE_CSV
    docker compose exec minio bash \
        -c "mc cp --recursive /temp/* $MINIO_ALIAS/$MINIO_BUCKET/data/"
    docker compose exec minio bash \
        -c "rm -rf /temp"
  fi
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Build Docker images and create database structure.
        echo "Building Docker images and creating database structure..."
        ./scripts/update

        # Fix permissions for the static folder before running collectstatic
        echo "Fixing permissions for the static folder..."
        docker compose run --rm --entrypoint sh django -c \
            "mkdir -p /usr/local/src/static/static && \
            chmod -R 755 /usr/local/src/static/static"

        # Collect Django static files
        echo "Collecting Django static files..."
        docker compose \
            run --rm --entrypoint python \
            django \
            manage.py collectstatic --noinput

        # Setup MinIO backend for local development
        setup_minio

        # Populate database with seeded facility lists.
        echo "Populating database with seeded facility lists..."
        ./scripts/reset_database

        # Start Docker DedupeHub and Kafka containers in the background for
        # matching.
        echo "Starting Docker DedupeHub and Kafka containers..."
        docker compose up -d api-app init-kafka

        # Wait for the services to be up and running (optional sleep to allow
        # all containers to initialize).
        echo "Waiting 60 seconds for services to be fully up and running..."
        sleep 60

        # Launch deduplication process of seeded lists to create new facilities.
        echo "Launching deduplication process of seeded lists..."
        ./scripts/manage matchfixtures

        # Wait for the matching to finish.
        echo "Waiting 60 seconds for matching to finish..."
        sleep 60

        # Launch the rest of the services.
        echo "Launching the rest of the services..."
        docker compose up -d

        echo "Process completed successfully!"
    fi
fi
