#!/bin/bash

set -e

if [[ -n "${OAR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build container images and execute database migrations.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Ensure container images are current
        docker compose build

        # Bring up PostgreSQL and Django in a way that respects
        # configured service health checks.
        docker compose up -d database django minio

        # Apply any outstanding Django migrations
        docker compose \
            run --rm --entrypoint python \
            django \
            manage.py migrate --no-input
    fi
fi
