FROM node:22-slim

WORKDIR /usr/local/src

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

# Watcher polling and port are configured in vite.config.js.
ENV REACT_APP_GIT_COMMIT=${REACT_APP_GIT_COMMIT:-latest}

CMD ["yarn","start"]
