FROM postgis/postgis:12-3.4-alpine

WORKDIR /opt/

RUN set -ex && apk update && apk add --no-cache openssh-client
RUN set -ex && apk update && apk add --no-cache aws-cli
ENV POSTGRES_PASSWORD=anondb
ENV POSTGRES_USER=anondb
ENV POSTGRES_DB=anondb

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION

RUN mkdir -p /dumps/
RUN mkdir -p /keys/

COPY ./do_restore.sh ./

VOLUME /keys

CMD ["sh", "do_restore.sh"]

