FROM postgis/postgis:12-3.4-alpine

WORKDIR /opt/

RUN echo "Hello, World!"
COPY ./do_work.sh ./do_work.sh
COPY ./initdb.sql /docker-entrypoint-initdb.d
ENV POSTGRES_PASSWORD=anondb
ENV POSTGRES_USER=anondb
ENV POSTGRES_DB=anondb
RUN set -ex && apk update && apk add openssh-client
RUN mkdir -p /dumps/
RUN mkdir -p /keys/
RUN mkdir ~/.ssh
VOLUME /dumps/
VOLUME /keys
# ENTRYPOINT [ "docker-entrypoint.sh" ]
CMD ["sh", "do_work.sh"]

