name: Code Quality Django

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  get-base-branch-django-cov:
    environment: Quality Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
      - name: Create required env file
        run: |
          echo '${{ secrets.CODE_QUALITY_ENV_FILE }}' > .env
      - name: Build Django image
        run: docker-compose build
      - name: Run the unittest tests and generate code cov report
        run: |
          docker-compose \
            run --rm --entrypoint /bin/sh django \
            -c "coverage run --data-file=./coverage/django/.coverage manage.py test --no-input ./api/tests \
            && coverage lcov --data-file=./coverage/django/.coverage -o ./coverage/django/coverage.lcov \
            --include='./api/*' --omit='./api/migrations/*,./api/tests/*'"
      - name: Upload unittest code cov for the base branch
        uses: actions/upload-artifact@v4
        with:
          name: base-branch-django-unittest-code-cov
          path: ./src/django/coverage/django/coverage.lcov
  run-django-code-quality:
    environment: Quality Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create required env file
        run: |
          echo '${{ secrets.CODE_QUALITY_ENV_FILE }}' > .env
      - name: Build Django image
        run: docker-compose build
      # - name: Run the Flake8 linter check
      #   run: |
      #     docker-compose \
      #       run --rm --no-deps --entrypoint flake8 django \
      #       --exclude settings.py,manage.py,*.pyc,api/migrations/*
      - name: Run the unittest tests and generate code cov report
        run: |
          docker-compose \
            run --rm --entrypoint /bin/sh django \
            -c "coverage run --data-file=./coverage/django/.coverage manage.py test --no-input ./api/tests \
            && coverage lcov --data-file=./coverage/django/.coverage -o ./coverage/django/coverage.lcov \
            --include='./api/*' --omit='./api/migrations/*,./api/tests/*'"
      - name: Upload unittest code cov for the feature branch
        uses: actions/upload-artifact@v4
        with:
          name: feature-branch-django-unittest-code-cov
          path: ./src/django/coverage/django/coverage.lcov
  check-django-code-cov:
    environment: Quality Environment
    needs:
      - get-base-branch-django-cov
      - run-django-code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Download unittest code cov reports
        uses: actions/download-artifact@v4
        with:
          pattern: "*-unittest-code-cov"
      - name: Verify unittest code cov
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./feature-branch-django-unittest-code-cov/coverage.lcov"
          base-lcov-file: "./base-branch-django-unittest-code-cov/coverage.lcov"
          minimum-ratio: 1
          send-summary-comment: true
          show-annotations: "warning"
          app-name: Django App | Unittest test suite
