name: "DB - Save Anonymized DB"

on:
  workflow_dispatch:

jobs:
  save-anonymized-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save Anonymized DB
        run: |
          echo "Save Anonymized DB"
          echo "DB saved!"