name: "DB - Save Anonimized DB"

on:
  workflow_dispatch:

jobs:
  save-anonimized-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save Anonimized DB
        run: |
          echo "Save Anonimized DB"
          echo "DB saved!"