name: Weekly issue metrics
on:
  push:
    branches:
      - issue-metrics-workflow
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
    - name: Get dates for last week
      shell: bash
      run: |
        # Calculate the end date, which is today
        end_date=$(date +%Y-%m-%d)

        # Calculate the start date, which is 7 days ago
        start_date=$(date -d "$end_date -7 days" +%Y-%m-%d)

        #Set an environment variable with the date range
        echo "$start_date..$end_date"
        echo "last_week=$start_date..$end_date" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v3
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:owner/repo is:pr created:${{ env.last_week }} -reason:"not planned"'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: Weekly issue metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md