name: '[Release] Init'

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version (e.g. 1.8)'
        required: true
        type: string
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: print ref
        run: echo ${{ github.ref }}
      # - name: Checkout repo
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.ref }}
      
      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: refs/heads/releases/v.${{ inputs.release-version }}
          sha: '${{ github.sha }}'
