name: 'Test slave'

on:
  workflow_dispatch:
    inputs:
      deploy-env:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - Development
          - Test
          - Pre-prod
          - Staging
          - Production
        default: Development
      clear-opensearch:
        description: 'Clear OpenSearch indexes'
        required: false
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show input parameters
        run: |
          echo "Tag: ${{ github.event.inputs.tag }}"
          echo "clear-opensearch: ${{ github.event.inputs.clear-opensearch }}, default: ${{ inputs.clear-opensearch }}"
          echo "deploy-env: ${{ github.event.inputs.deploy-env }}, default: ${{ inputs.deploy-env }}"
